import type { FaqItem } from "../types";

/** Category 8 — AI Assistant / KI-Assistent */
export const aiAssistantItems: FaqItem[] = [
  {
    id: "aa-what",
    category: "ai-assistant",
    question: {
      de: "Was ist der KI-Assistent?",
      en: "What is the AI Assistant?",
      fr: "Qu'est-ce que l'Assistant IA ?",
      ar: "ما هو المساعد الذكي؟",
    },
    answer: {
      de: "Der KI-Assistent ist Ihr Gesprächspartner in der Plattform für Fragen rund um Ausbildung, Jobs in Deutschland, Bewerbungen, Lebenslauf, Anschreiben und die Nutzung der Plattform.",
      en: "The AI Assistant is your conversational partner in the platform for questions about apprenticeships, jobs in Germany, applications, CV, cover letter and using the platform.",
      fr: "L'Assistant IA est votre interlocuteur dans la plateforme pour les questions sur l'alternance, les emplois en Allemagne, les candidatures, le CV, la lettre de motivation et l'utilisation de la plateforme.",
      ar: "المساعد الذكي هو شريكك في الحوار داخل المنصّة للإجابة عن أسئلة التدريب المهني والعمل في ألمانيا وطلبات التقديم والسيرة الذاتية وخطاب التقديم واستخدام المنصّة.",
    },
    keywords: ["ai assistant", "chat", "what"],
  },
  {
    id: "aa-ask-what",
    category: "ai-assistant",
    question: {
      de: "Was kann ich den KI-Assistenten fragen?",
      en: "What can I ask the AI Assistant?",
      fr: "Que puis-je demander à l'Assistant IA ?",
      ar: "ما الذي يمكنني سؤاله؟",
    },
    answer: {
      de: "Alles, was zu Ausbildung, Jobs in Deutschland, Bewerbungen, Lebenslauf, Anschreiben und der Plattform passt – etwa wie Sie eine Bewerbung aufbauen, wie ein Anschreiben klingen kann oder wie Sie mit einem Angebot umgehen.",
      en: "Anything related to apprenticeships, jobs in Germany, applications, CV, cover letter and the platform – e.g. how to build an application, how a cover letter might sound, or how to handle a listing.",
      fr: "Tout ce qui concerne l'alternance, les emplois en Allemagne, les candidatures, le CV, la lettre de motivation et la plateforme – par exemple comment construire une candidature, à quoi peut ressembler une lettre, ou comment aborder une offre.",
      ar: "كل ما يتعلق بالتدريب المهني والعمل في ألمانيا وطلبات التقديم والسيرة الذاتية وخطاب التقديم والمنصّة — مثل كيف تبني طلبك، أو كيف يبدو خطاب تقديم، أو كيف تتعامل مع إعلان.",
    },
    keywords: ["ask", "questions", "topics"],
  },
  {
    id: "aa-help-ausbildung",
    category: "ai-assistant",
    question: {
      de: "Kann er mir bei der Ausbildung helfen?",
      en: "Can it help me with apprenticeships?",
      fr: "Peut-il m'aider pour l'alternance ?",
      ar: "هل يمكنه مساعدتي في التدريب المهني؟",
    },
    answer: {
      de: "Ja. Er erklärt Ausbildungswege, hilft bei Fragen zu Berufen und berät, wie Sie passende Angebote bewerten und bewerben.",
      en: "Yes. It explains apprenticeship paths, helps with questions about professions and advises how to evaluate and apply to suitable listings.",
      fr: "Oui. Il explique les parcours de formation, aide à des questions sur les métiers et conseille comment évaluer et candidater aux offres adaptées.",
      ar: "نعم. يشرح مسارات التدريب المهني ويساعد في أسئلة المهن وينصحه بكيفية تقييم الإعلانات المناسبة والتقديم إليها.",
    },
    keywords: ["ausbildung", "help", "apprenticeship"],
  },
  {
    id: "aa-help-bewerbung",
    category: "ai-assistant",
    question: {
      de: "Kann er mir bei der Bewerbung helfen?",
      en: "Can it help me with my application?",
      fr: "Peut-il m'aider pour ma candidature ?",
      ar: "هل يمكنه مساعدتي في الطلب؟",
    },
    answer: {
      de: "Ja. Er gibt Tipps zu Aufbau, Inhalt und Formulierung Ihrer Bewerbung und erklärt, worauf es bei deutschen Bewerbungen ankommt.",
      en: "Yes. It gives tips on the structure, content and wording of your application and explains what matters in German applications.",
      fr: "Oui. Il donne des conseils sur la structure, le contenu et la formulation de votre candidature et explique ce qui compte dans les candidatures allemandes.",
      ar: "نعم. يقدم نصائح حول هيكل الطلب ومحتواه وصياغته، ويشرح ما يهم في طلبات التقديم الألمانية.",
    },
    keywords: ["bewerbung", "application", "help"],
  },
  {
    id: "aa-help-cv",
    category: "ai-assistant",
    question: {
      de: "Kann er mir bei meinem Lebenslauf helfen?",
      en: "Can it help me with my CV?",
      fr: "Peut-il m'aider avec mon CV ?",
      ar: "هل يمكنه مساعدتي في سيرتي الذاتية؟",
    },
    answer: {
      de: "Ja. Er berät zu Aufbau, Inhalt und Formulierung Ihres Lebenslaufs. Sie können ihm auch Ihr CV als Datei schicken, damit er es einordnen und verbessern kann.",
      en: "Yes. It advises on the structure, content and wording of your CV. You can also send it your CV as a file so it can assess and improve it.",
      fr: "Oui. Il conseille sur la structure, le contenu et la formulation de votre CV. Vous pouvez aussi lui envoyer votre CV en fichier pour qu'il l'évalue et l'améliore.",
      ar: "نعم. ينصحه بشأن هيكل سيرتك ومحتواها وصياغتها. كما يمكنك إرسال سيرتك كملف ليقيّمها ويحسّنها.",
    },
    keywords: ["cv", "lebenslauf", "help"],
  },
  {
    id: "aa-help-anschreiben",
    category: "ai-assistant",
    question: {
      de: "Kann er mir bei meinem Anschreiben helfen?",
      en: "Can it help me with my cover letter?",
      fr: "Peut-il m'aider avec ma lettre de motivation ?",
      ar: "هل يمكنه مساعدتي في خطاب التقديم؟",
    },
    answer: {
      de: "Ja. Er hilft beim Formulieren und Aufbau Ihres Anschreibens und erklärt, welche Elemente ein gutes Anschreiben enthält.",
      en: "Yes. It helps with the wording and structure of your cover letter and explains what elements a good cover letter contains.",
      fr: "Oui. Il aide à la formulation et à la structure de votre lettre de motivation et explique les éléments d'une bonne lettre.",
      ar: "نعم. يساعدك في صياغة خطاب التقديم وبنائه، ويشرح العناصر التي يمتلئ بها خطاب جيد.",
    },
    keywords: ["anschreiben", "cover letter", "help"],
  },
  {
    id: "aa-analyze-pdf",
    category: "ai-assistant",
    question: {
      de: "Kann er ein PDF analysieren?",
      en: "Can it analyze a PDF?",
      fr: "Peut-il analyser un PDF ?",
      ar: "هل يمكنه تحليل ملف PDF؟",
    },
    answer: {
      de: "Ja. Sie können ihm Dateien wie PDF, DOC oder DOCX schicken – er liest den Inhalt und antwortet darauf. Pro Datei gilt eine Größenbegrenzung von 10 MB.",
      en: "Yes. You can send it files like PDF, DOC or DOCX – it reads the content and answers based on it. Each file is limited to 10 MB.",
      fr: "Oui. Vous pouvez lui envoyer des fichiers comme PDF, DOC ou DOCX – il lit le contenu et y répond. Chaque fichier est limité à 10 Mo.",
      ar: "نعم. يمكنك إرسال ملفات مثل PDF أو DOC أو DOCX — يقرأ المحتوى ويجيب بناءً عليه. وحجم كل ملف محدود بـ 10 ميغابايت.",
    },
    keywords: ["pdf", "analyze", "file"],
  },
  {
    id: "aa-upload",
    category: "ai-assistant",
    question: {
      de: "Kann ich dem Assistenten eine Datei schicken?",
      en: "Can I send the assistant a file?",
      fr: "Puis-je envoyer un fichier à l'assistant ?",
      ar: "هل يمكنني إرسال ملف للمساعد؟",
    },
    answer: {
      de: "Ja. Sie können Dateien anhängen, damit der Assistent sie mitliest. Unterstützt werden PDF, DOC, DOCX, TXT sowie Bilder (PNG, JPG, JPEG, WEBP).",
      en: "Yes. You can attach files so the assistant reads them along. Supported are PDF, DOC, DOCX, TXT and images (PNG, JPG, JPEG, WEBP).",
      fr: "Oui. Vous pouvez joindre des fichiers pour que l'assistant les lise. Sont pris en charge PDF, DOC, DOCX, TXT et des images (PNG, JPG, JPEG, WEBP).",
      ar: "نعم. يمكنك إرفاق ملفات ليقرأها المساعد. الأنواع المدعومة: PDF وDOC وDOCX وTXT والصور (PNG وJPG وJPEG وWEBP).",
    },
    keywords: ["upload", "file", "attach"],
  },
  {
    id: "aa-file-limits",
    category: "ai-assistant",
    question: {
      de: "Wie viele und welche Dateien kann ich schicken?",
      en: "How many and which files can I send?",
      fr: "Combien et quels fichiers puis-je envoyer ?",
      ar: "كم ملفًا وأي أنواع يمكنني إرسالها؟",
    },
    answer: {
      de: "Je Nachricht können mehrere Dateien angehängt werden, pro Datei maximal 10 MB. Für die Auswertung liest der Server bei jedem Vorgang bis zu fünf Dateien ein.",
      en: "You can attach several files per message, at most 10 MB each. For evaluation, the server reads up to five files per request.",
      fr: "Vous pouvez joindre plusieurs fichiers par message, au plus 10 Mo chacun. Pour l'évaluation, le serveur lit jusqu'à cinq fichiers par requête.",
      ar: "يمكنك إرفاق عدة ملفات في الرسالة، بحد أقصى 10 ميغابايت لكل ملف. وللإنشاء يقرأ الخادم حتى خمس ملفات في كل طلب.",
    },
    keywords: ["files", "limits", "count"],
  },
  {
    id: "aa-explain-listing",
    category: "ai-assistant",
    question: {
      de: "Kann er mir eine Stellenanzeige erklären?",
      en: "Can it explain a job listing to me?",
      fr: "Peut-il m'expliquer une offre d'emploi ?",
      ar: "هل يمكنه شرح إعلان وظيفة لي؟",
    },
    answer: {
      de: "Ja. Sie können den Text oder die Datei einer Anzeige teilen – der Assistent fasst Anforderungen, Rahmenbedingungen und passende nächste Schritte zusammen.",
      en: "Yes. You can share the text or file of a listing – the assistant summarizes the requirements, conditions and sensible next steps.",
      fr: "Oui. Vous pouvez partager le texte ou le fichier d'une offre – l'assistant résume les exigences, les conditions et les prochaines étapes appropriées.",
      ar: "نعم. يمكنك مشاركة نص الإعلان أو ملفه — يلخّص المساعد المتطلبات والشروط والخطوات التالية المناسبة.",
    },
    keywords: ["listing", "explain", "stelle"],
  },
  {
    id: "aa-followup",
    category: "ai-assistant",
    question: {
      de: "Kann ich Folgefragen stellen?",
      en: "Can I ask follow-up questions?",
      fr: "Puis-je poser des questions de suivi ?",
      ar: "هل يمكنني طرح أسئلة متابعة؟",
    },
    answer: {
      de: "Ja. Das Gespräch verläuft im Kontext: Sie können auf vorherige Antworten aufbauen und vertiefen.",
      en: "Yes. The conversation runs in context: you can build on previous answers and go deeper.",
      fr: "Oui. La conversation se déroule dans son contexte : vous pouvez vous appuyer sur les réponses précédentes et approfondir.",
      ar: "نعم. يتدفق الحوار في سياقه: يمكنك البناء على الإجابات السابقة والتعمق فيها.",
    },
    keywords: ["followup", "context", "conversation"],
  },
  {
    id: "aa-remembers",
    category: "ai-assistant",
    question: {
      de: "Merkt er sich das Gespräch?",
      en: "Does it remember the conversation?",
      fr: "Se souvient-il de la conversation ?",
      ar: "هل يتذكر المحادثة؟",
    },
    answer: {
      de: "Innerhalb eines Gesprächs ja: Die bisherigen Nachrichten fließen in die Antworten ein. So bleibt der Zusammenhang erhalten.",
      en: "Within a conversation, yes: the previous messages feed into the answers, so the context is preserved.",
      fr: "Dans une conversation, oui : les messages précédents alimentent les réponses, ce qui préserve le contexte.",
      ar: "ضمن المحادثة، نعم: الرسائل السابقة تشارك في الإجابات، فيبقى السياق محفوظًا.",
    },
    keywords: ["memory", "context", "remembers"],
  },
  {
    id: "aa-saved",
    category: "ai-assistant",
    question: {
      de: "Wird das Gespräch gespeichert?",
      en: "Is the conversation saved?",
      fr: "La conversation est-elle enregistrée ?",
      ar: "هل تُحفظ المحادثة؟",
    },
    answer: {
      de: "Ja. Ihre Gespräche werden in Ihrem Konto gespeichert und bleiben in Ihrem Verlauf verfügbar.",
      en: "Yes. Your conversations are saved in your account and remain available in your history.",
      fr: "Oui. Vos conversations sont enregistrées dans votre compte et restent disponibles dans votre historique.",
      ar: "نعم. تُحفظ محادثاتك في حسابك وتبقى متاحة في سجلك.",
    },
    keywords: ["saved", "history", "persist"],
  },
  {
    id: "aa-after-refresh",
    category: "ai-assistant",
    question: {
      de: "Was passiert nach einem Refresh?",
      en: "What happens after a refresh?",
      fr: "Que se passe-t-il après un rechargement ?",
      ar: "ماذا يحدث بعد إعادة التحميل؟",
    },
    answer: {
      de: "Ihr gespeichertes Gespräch bleibt erhalten – nach dem Neuladen finden Sie Ihre bisherigen Nachrichten wieder.",
      en: "Your saved conversation remains – after reloading you find your previous messages again.",
      fr: "Votre conversation enregistrée reste – après le rechargement, vous retrouvez vos messages précédents.",
      ar: "تبقى محادثتك المحفوظة — بعد إعادة التحميل تجد رسائل السابقة مجددًا.",
    },
    keywords: ["refresh", "reload", "persist"],
  },
  {
    id: "aa-after-logout",
    category: "ai-assistant",
    question: {
      de: "Was passiert nach Logout und Login?",
      en: "What happens after logout and login?",
      fr: "Que se passe-t-il après déconnexion et connexion ?",
      ar: "ماذا يحدث بعد تسجيل الخروج والدخول؟",
    },
    answer: {
      de: "Ihre Gespräche sind an Ihr Konto gebunden. Nach dem erneuten Anmelden sind sie wieder verfügbar.",
      en: "Your conversations are bound to your account. After signing back in, they are available again.",
      fr: "Vos conversations sont liées à votre compte. Après la reconnexion, elles sont de nouveau disponibles.",
      ar: "محادثاتك مرتبطة بحسابك. بعد تسجيل الدخول مجددًا تصبح متاحة من جديد.",
    },
    keywords: ["logout", "login", "account"],
  },
  {
    id: "aa-why-streams",
    category: "ai-assistant",
    question: {
      de: "Warum beginnt die KI zu schreiben, bevor die Antwort fertig ist?",
      en: "Why does the AI start typing before the answer is complete?",
      fr: "Pourquoi l'IA commence-t-elle à écrire avant que la réponse ne soit finie ?",
      ar: "لماذا يبدأ الذكاء الاصطناعي بالكتابة قبل اكتمال الإجابة؟",
    },
    answer: {
      de: "Die Antwort wird schrittweise übertragen (Streaming): So sehen Sie, dass die KI bereits arbeitet, ohne auf das komplette Ergebnis warten zu müssen.",
      en: "The answer is delivered progressively (streaming): you can see the AI is already working without having to wait for the full result.",
      fr: "La réponse est transmise progressivement (streaming) : vous voyez que l'IA travaille déjà sans attendre le résultat complet.",
      ar: "تُرسَل الإجابة تدريجيًا: هكذا ترى أن الذكاء الاصطناعي يعمل بالفعل دون انتظار النتيجة الكاملة.",
    },
    keywords: ["streaming", "typing", "progressive"],
  },
  {
    id: "aa-stop",
    category: "ai-assistant",
    question: {
      de: "Kann ich die Antwort stoppen?",
      en: "Can I stop the answer?",
      fr: "Puis-je arrêter la réponse ?",
      ar: "هل يمكنني إيقاف الإجابة؟",
    },
    answer: {
      de: "Ja. Mit dem Stopp-Button unterbrechen Sie die laufende Antwort. Bis dahin Geschriebene bleibt erhalten.",
      en: "Yes. With the Stop button you interrupt the running answer. What has been written so far is kept.",
      fr: "Oui. Avec le bouton d'arrêt, vous interrompez la réponse en cours. Ce qui a été écrit jusque-là est conservé.",
      ar: "نعم. باستخدام زر الإيقاف تقاطع الإجابة الجارية. وما كُتب حتى تلك اللحظة يبقى محفوظًا.",
    },
    keywords: ["stop", "interrupt", "button"],
  },
  {
    id: "aa-stop-result",
    category: "ai-assistant",
    question: {
      de: "Was passiert, wenn ich auf Stopp klicke?",
      en: "What happens when I click Stop?",
      fr: "Que se passe-t-il quand je clique sur Arrêter ?",
      ar: "ماذا يحدث عندما أنقر على إيقاف؟",
    },
    answer: {
      de: "Die Übertragung wird beendet und der bisherige Antworttext bleibt in Ihrem Gespräch stehen. Sie können jederzeit eine neue Frage stellen.",
      en: "The delivery stops and the answer text so far remains in your conversation. You can ask a new question any time.",
      fr: "La transmission s'arrête et le texte de réponse jusqu'ici reste dans votre conversation. Vous pouvez poser une nouvelle question à tout moment.",
      ar: "تتوقف الإرسال ويبقى نص الإجابة حتى تلك اللحظة في محادثتك. يمكنك طرح سؤال جديد في أي وقت.",
    },
    keywords: ["stop", "result", "partial"],
  },
  {
    id: "aa-fail",
    category: "ai-assistant",
    question: {
      de: "Was passiert, wenn die KI fehlschlägt?",
      en: "What happens if the AI fails?",
      fr: "Que se passe-t-il si l'IA échoue ?",
      ar: "ماذا يحدث إذا فشل الذكاء الاصطناعي؟",
    },
    answer: {
      de: "Dann sehen Sie eine kurze Fehlermeldung. Ihre bisherige Unterhaltung bleibt erhalten und Sie können es erneut versuchen.",
      en: "Then you see a short error message. Your conversation so far remains and you can try again.",
      fr: "Alors vous voyez un court message d'erreur. Votre conversation jusqu'ici reste et vous pouvez réessayer.",
      ar: "في هذه الحالة ترى رسالة خطأ قصيرة. وتبقى محادثتك حتى تلك اللحظة وتتمكن من إعادة المحاولة.",
    },
    keywords: ["fail", "error", "ai"],
  },
  {
    id: "aa-retry",
    category: "ai-assistant",
    question: {
      de: "Kann ich die Antwort erneut versuchen?",
      en: "Can I retry the answer?",
      fr: "Puis-je réessayer la réponse ?",
      ar: "هل يمكنني إعادة المحاولة؟",
    },
    answer: {
      de: "Ja. Sie können Ihre Frage erneut stellen oder die Aktion wiederholen, um eine neue Antwort zu erhalten.",
      en: "Yes. You can ask your question again or repeat the action to get a new answer.",
      fr: "Oui. Vous pouvez redemander votre question ou répéter l'action pour obtenir une nouvelle réponse.",
      ar: "نعم. يمكنك طرح سؤالك مجددًا أو تكرار الإجراء للحصول على إجابة جديدة.",
    },
    keywords: ["retry", "again", "retry"],
  },
  {
    id: "aa-refuse",
    category: "ai-assistant",
    question: {
      de: "Warum verweigert die KI manche Fragen?",
      en: "Why does the AI refuse some questions?",
      fr: "Pourquoi l'IA refuse-t-elle certaines questions ?",
      ar: "لماذا يرفض الذكاء الاصطناعي بعض الأسئلة؟",
    },
    answer: {
      de: "Der Assistent ist auf den Bereich der Plattform spezialisiert. Fragen, die deutlich außerhalb davon liegen, werden höflich abgelehnt oder auf das Thema zurückgeführt.",
      en: "The assistant is specialized to the platform's domain. Questions that clearly fall outside it are politely declined or redirected back to the topic.",
      fr: "L'assistant est spécialisé dans le domaine de la plateforme. Les questions qui en sortent clairement sont poliment refusées ou redirigées vers le sujet.",
      ar: "المساعد متخصص في مجال المنصّة. الأسئلة التي تخرج بوضوح عن هذا المجال تُرفض بلطف أو يُعاد توجيهها إلى الموضوع.",
    },
    keywords: ["refuse", "decline", "scope"],
  },
  {
    id: "aa-no-topics",
    category: "ai-assistant",
    question: {
      de: "Worüber antwortet die KI nicht?",
      en: "What does the AI not answer about?",
      fr: "Sur quoi l'IA ne répond-elle pas ?",
      ar: "عن أي مواضيع لا يجيب؟",
    },
    answer: {
      de: "Nicht über Themen weit außerhalb von Ausbildung, Jobs in Deutschland, Bewerbungen, Lebenslauf, Anschreiben und der Plattform – etwa allgemeine Unterhaltung oder fachfremde Anfragen.",
      en: "Not about topics far outside apprenticeships, jobs in Germany, applications, CV, cover letter and the platform – e.g. general small talk or unrelated requests.",
      fr: "Pas sur des sujets loin de l'alternance, des emplois en Allemagne, des candidatures, du CV, de la lettre de motivation et de la plateforme – par exemple la simple conversation ou des demandes sans rapport.",
      ar: "لا يجيب عن المواضيع البعيدة عن التدريب والعمل في ألمانيا وطلبات التقديم والسيرة الذاتية وخطاب التقديم والمنصّة — مثل الأحاديث العامة أو الطلبات غير المرتبطة.",
    },
    keywords: ["no topics", "scope", "refuse"],
  },
  {
    id: "aa-general-chatbot",
    category: "ai-assistant",
    question: {
      de: "Ist der KI-Assistent ein allgemeiner Chatbot?",
      en: "Is the AI Assistant a general chatbot?",
      fr: "L'Assistant IA est-il un chatbot général ?",
      ar: "هل المساعد الذكي روبوت محادثة عام؟",
    },
    answer: {
      de: "Nein. Er ist kein allgemeiner Chatbot, sondern ein Assistent, der auf Ausbildung, Jobs in Deutschland, Bewerbungen, Lebenslauf, Anschreiben und die Plattform spezialisiert ist.",
      en: "No. It is not a general chatbot, but an assistant specialized in apprenticeships, jobs in Germany, applications, CV, cover letter and the platform.",
      fr: "Non. Ce n'est pas un chatbot général, mais un assistant spécialisé dans l'alternance, les emplois en Allemagne, les candidatures, le CV, la lettre de motivation et la plateforme.",
      ar: "لا. ليس روبوت محادثة عامًا، بل مساعد متخصص في التدريب والعمل في ألمانيا وطلبات التقديم والسيرة الذاتية وخطاب التقديم والمنصّة.",
    },
    keywords: ["general", "chatbot", "specialized"],
  },
  {
    id: "aa-specialized",
    category: "ai-assistant",
    question: {
      de: "Ist er auf AusbildungsWeg spezialisiert?",
      en: "Is it specialized in AusbildungsWeg?",
      fr: "Est-il spécialisé dans AusbildungsWeg ?",
      ar: "هل هو متخصص في AusbildungsWeg؟",
    },
    answer: {
      de: "Ja. Der Assistent ist als dedizierter Fachassistent für diese Plattform konzipiert und orientiert sich an ihren Tools und Ihrem Bewerbungskontext.",
      en: "Yes. The assistant is designed as a dedicated specialist for this platform and aligns with its tools and your application context.",
      fr: "Oui. L'assistant est conçu comme spécialiste dédié à cette plateforme et s'aligne sur ses outils et votre contexte de candidature.",
      ar: "نعم. صُمم المساعد كمختص مخصص لهذه المنصّة ويتوافق مع أدواتها وسياق تقديمك.",
    },
    keywords: ["specialized", "platform", "dedicated"],
  },
  {
    id: "aa-out-of-domain",
    category: "ai-assistant",
    question: {
      de: "Kann er Fragen außerhalb des Ausbildungsbereichs beantworten?",
      en: "Can it answer questions outside the apprenticeship domain?",
      fr: "Peut-il répondre à des questions en dehors du domaine de l'alternance ?",
      ar: "هل يمكنه الإجابة عن أسئلة خارج مجال التدريب؟",
    },
    answer: {
      de: "Nur, wenn sie zu Bewerbung, Jobs in Deutschland, Lebenslauf, Anschreiben oder der Plattform passen. Rein fremde Themen liegen außerhalb seines Auftrags.",
      en: "Only if they relate to applications, jobs in Germany, CV, cover letter or the platform. Purely unrelated topics are outside its mandate.",
      fr: "Seulement si elles concernent la candidature, les emplois en Allemagne, le CV, la lettre de motivation ou la plateforme. Les sujets sans rapport sont hors de son périmètre.",
      ar: "فقط إذا كانت تتعلق بالتقديم والعمل في ألمانيا والسيرة الذاتية وخطاب التقديم والمنصّة. أما المواضيع غير المرتبطة فتخرج عن مهامه.",
    },
    keywords: ["out of domain", "scope", "unrelated"],
  },
  {
    id: "aa-invent-jobs",
    category: "ai-assistant",
    question: {
      de: "Kann er Jobs, Firmen oder Links erfinden?",
      en: "Can it invent jobs, companies or links?",
      fr: "Peut-il inventer des postes, des entreprises ou des liens ?",
      ar: "هل يمكنه اختراع وظائف أو شركات أو روابط؟",
    },
    answer: {
      de: "Nein. Der Assistent erfindet keine konkreten Jobs, Firmen oder Links. Er berät allgemein und arbeitet mit den Daten, die Sie ihm geben – er verlinkt nichts, was er nicht kennt.",
      en: "No. The assistant does not invent specific jobs, companies or links. It advises in general and works with the data you give it – it does not link anything it does not know.",
      fr: "Non. L'assistant n'invente ni postes, ni entreprises, ni liens concrets. Il conseille de façon générale et travaille avec les données que vous lui donnez – il ne lie rien qu'il ne connaît pas.",
      ar: "لا. لا يخترع المساعد وظائف أو شركات أو روابط محددة. ينصح بشكل عام ويعمل بالبيانات التي تزوّده بها — ولا يربط بما لا يعرفه.",
    },
    keywords: ["invent", "jobs", "links", "companies"],
  },
  {
    id: "aa-daily-limit",
    category: "ai-assistant",
    question: {
      de: "Gibt es ein tägliches Limit für die KI?",
      en: "Is there a daily limit for the AI?",
      fr: "Y a-t-il une limite quotidienne pour l'IA ?",
      ar: "هل يوجد حد يومي للذكاء الاصطناعي؟",
    },
    answer: {
      de: "Ja. Pro Tag steht Ihnen eine Anzahl an KI-Anfragen zur Verfügung. Erreichen Sie das Limit, erhalten Sie eine kurze Mitteilung und können am nächsten Tag weitermachen. Die genaue Höhe hängt von Ihrem Plan ab.",
      en: "Yes. A number of AI requests per day is available to you. When you reach the limit, you get a short notice and can continue the next day. The exact amount depends on your plan.",
      fr: "Oui. Un nombre de requêtes IA par jour vous est disponible. Lorsque vous atteignez la limite, vous recevez une brève notification et pouvez reprendre le lendemain. Le montant exact dépend de votre plan.",
      ar: "نعم. يتوفر لك عدد من طلبات الذكاء الاصطناعي يوميًا. عند بلوغ الحد تصلك رسالة موجزة وتستأنف في اليوم التالي. والحد الفعلي يعتمد على خطتك.",
    },
    keywords: ["limit", "daily", "ai"],
  },
];
