import type { FaqItem } from "../types";

/** Category 10 — CV Templates / CV-Vorlagen */
export const cvTemplatesItems: FaqItem[] = [
  {
    id: "cv-what",
    category: "cv-templates",
    question: {
      de: "Was sind die Vorlagen?",
      en: "What are the templates?",
      fr: "Que sont les modèles ?",
      ar: "ما هي القوالب؟",
    },
    answer: {
      de: "Die Vorlagen bieten Ihnen einen Builder für Ihren Lebenslauf: Sie füllen die Bereiche aus, sehen eine Live-Vorschau und können Ihr CV als PDF herunterladen.",
      en: "The templates give you a CV builder: you fill in the sections, see a live preview and can download your CV as PDF.",
      fr: "Les modèles vous offrent un éditeur de CV : vous remplissez les sections, voyez une aperçu en direct et pouvez télécharger votre CV en PDF.",
      ar: "تقدم لك القوالب أداة لبناء سيرتك الذاتية: تملأ الأقسام وترى معاينة حيوية ويمكنك تنزيل سيرتك كملف PDF.",
    },
    keywords: ["templates", "cv", "builder"],
  },
  {
    id: "cv-how-create",
    category: "cv-templates",
    question: {
      de: "Wie erstelle ich einen Lebenslauf?",
      en: "How do I create a CV?",
      fr: "Comment créer un CV ?",
      ar: "كيف أنشئ سيرة ذاتية؟",
    },
    answer: {
      de: "Öffnen Sie Vorlagen und füllen Sie die Bereiche aus – von Ihren Angaben bis zu Erfahrung und Skills. Sie können zudem Ihr Profil aus dem Bewerbungsscan importieren.",
      en: "Open Templates and fill in the sections – from your details to experience and skills. You can also import your profile from the Application Scanner.",
      fr: "Ouvrez Modèles et remplissez les sections – de vos coordonnées à l'expérience et aux compétences. Vous pouvez aussi importer votre profil du Scan de candidature.",
      ar: "افتح القوالب واملأ الأقسام — من بياناتك إلى الخبرة والمهارات. كما يمكنك استيراد ملفك من ماسح الطلبات.",
    },
    keywords: ["create", "cv", "how"],
  },
  {
    id: "cv-professional-classic",
    category: "cv-templates",
    question: {
      de: "Was ist 'Professional Classic'?",
      en: "What is 'Professional Classic'?",
      fr: "Qu'est-ce que 'Professional Classic' ?",
      ar: "ما هو 'Professional Classic'؟",
    },
    answer: {
      de: "Professional Classic ist die verfügbare Vorlage: ein klarer, professioneller Aufbau, der sich für Bewerbungen in Deutschland eignet.",
      en: "Professional Classic is the available template: a clear, professional layout suited for applications in Germany.",
      fr: "Professional Classic est le modèle disponible : un agencement clair et professionnel, adapté aux candidatures en Allemagne.",
      ar: "Professional Classic هو القالب المتاح: تصميم واضح ومهني مناسب لطلبات التقديم في ألمانيا.",
    },
    keywords: ["professional classic", "template", "layout"],
  },
  {
    id: "cv-edit",
    category: "cv-templates",
    question: {
      de: "Wie bearbeite ich mein CV?",
      en: "How do I edit my CV?",
      fr: "Comment modifier mon CV ?",
      ar: "كيف أعدّل سيرتي؟",
    },
    answer: {
      de: "Bearbeiten Sie die Felder der Bereiche direkt. Ihre Änderungen erscheinen sofort in der Vorschau.",
      en: "Edit the fields of the sections directly. Your changes appear immediately in the preview.",
      fr: "Modifiez les champs des sections directement. Vos changements apparaissent immédiatement dans l'aperçu.",
      ar: "عدّل حقول الأقسام مباشرةً. وتظهر تغييراتك فورًا في المعاينة.",
    },
    keywords: ["edit", "cv", "fields"],
  },
  {
    id: "cv-add-experience",
    category: "cv-templates",
    question: {
      de: "Wie füge ich Erfahrung hinzu?",
      en: "How do I add experience?",
      fr: "Comment ajouter de l'expérience ?",
      ar: "كيف أضيف الخبرة؟",
    },
    answer: {
      de: "Im Bereich Erfahrung fügen Sie einen neuen Eintrag hinzu und geben Sie Stelle, Arbeitgeber und Zeitraum an.",
      en: "In the Experience section, add a new entry and provide the position, employer and period.",
      fr: "Dans la section Expérience, ajoutez une nouvelle entrée et indiquez le poste, l'employeur et la période.",
      ar: "في قسم الخبرة أضف مدخلًا جديدًا وحدد الوظيفة والموظف والفترة.",
    },
    keywords: ["experience", "add", "entry"],
  },
  {
    id: "cv-add-education",
    category: "cv-templates",
    question: {
      de: "Wie füge ich meine Ausbildung hinzu?",
      en: "How do I add my education?",
      fr: "Comment ajouter ma formation ?",
      ar: "كيف أضيف تعليمي؟",
    },
    answer: {
      de: "Im Bereich Bildung fügen Sie Einträge hinzu mit Schule, Abschluss und Zeitraum.",
      en: "In the Education section, add entries with school, qualification and period.",
      fr: "Dans la section Formation, ajoutez des entrées avec l'école, le diplôme et la période.",
      ar: "في قسم التعليم أضف مدخلات تتضمن المدرسة والشهادة والفترة.",
    },
    keywords: ["education", "add", "school"],
  },
  {
    id: "cv-add-skills",
    category: "cv-templates",
    question: {
      de: "Wie füge ich Skills hinzu?",
      en: "How do I add skills?",
      fr: "Comment ajouter des compétences ?",
      ar: "كيف أضيف المهارات؟",
    },
    answer: {
      de: "Im Bereich Kenntnisse fügen Sie Ihre Fähigkeiten hinzu – Sie können Einträge hinzufügen und anpassen.",
      en: "In the Skills section, add your abilities – you can add and adjust entries.",
      fr: "Dans la section Compétences, ajoutez vos capacités – vous pouvez ajouter et ajuster des entrées.",
      ar: "في قسم المهارات أضف قدراتك — يمكنك إضافة مدخلات وتعديلها.",
    },
    keywords: ["skills", "add", "competences"],
  },
  {
    id: "cv-add-languages",
    category: "cv-templates",
    question: {
      de: "Wie füge ich Sprachen hinzu?",
      en: "How do I add languages?",
      fr: "Comment ajouter des langues ?",
      ar: "كيف أضيف اللغات؟",
    },
    answer: {
      de: "Im Bereich Sprachen fügen Sie Sprachen mit ihrer Stufe hinzu (soweit bekannt).",
      en: "In the Languages section, add languages with their level (where known).",
      fr: "Dans la section Langues, ajoutez des langues avec leur niveau (le cas échéant).",
      ar: "في قسم اللغات أضف اللغات مع مستواها (إن كان معروفًا).",
    },
    keywords: ["languages", "add", "level"],
  },
  {
    id: "cv-add-certificates",
    category: "cv-templates",
    question: {
      de: "Wie füge ich Zertifikate hinzu?",
      en: "How do I add certificates?",
      fr: "Comment ajouter des certifications ?",
      ar: "كيف أضيف الشهادات؟",
    },
    answer: {
      de: "Im Bereich Zertifikate fügen Sie Ihre Nachweise und Weiterbildungen hinzu.",
      en: "In the Certificates section, add your credentials and further training.",
      fr: "Dans la section Certifications, ajoutez vos attestations et formations complémentaires.",
      ar: "في قسم الشهادات أضف إقراراتك وتدريبك الإضافي.",
    },
    keywords: ["certificates", "add", "credentials"],
  },
  {
    id: "cv-add-projects",
    category: "cv-templates",
    question: {
      de: "Wie füge ich Projekte hinzu?",
      en: "How do I add projects?",
      fr: "Comment ajouter des projets ?",
      ar: "كيف أضيف المشاريع؟",
    },
    answer: {
      de: "Im Bereich Projekte fügen Sie relevante Projekte hinzu, die Sie abgeschlossen haben.",
      en: "In the Projects section, add relevant projects you have completed.",
      fr: "Dans la section Projets, ajoutez des projets pertinents que vous avez réalisés.",
      ar: "في قسم المشاريع أضف مشاريع ذات صلة أكملتها.",
    },
    keywords: ["projects", "add"],
  },
  {
    id: "cv-photo",
    category: "cv-templates",
    question: {
      de: "Wie lade ich mein Foto hoch?",
      en: "How do I upload my photo?",
      fr: "Comment téléverser ma photo ?",
      ar: "كيف أرفع صورتي؟",
    },
    answer: {
      de: "Im Bereich Persönliches können Sie ein Foto hinzufügen. Erlaubt sind die Formate PNG und JPEG.",
      en: "In the Personal section you can add a photo. Allowed formats are PNG and JPEG.",
      fr: "Dans la section Personnel, vous pouvez ajouter une photo. Les formats autorisés sont PNG et JPEG.",
      ar: "في قسم البيانات الشخصية يمكنك إضافة صورة. الصيغ المسموح بها PNG وJPEG.",
    },
    keywords: ["photo", "upload", "picture"],
  },
  {
    id: "cv-photo-size",
    category: "cv-templates",
    question: {
      de: "Welche Größe ist für das Foto erlaubt?",
      en: "What size is allowed for the photo?",
      fr: "Quelle taille est autorisée pour la photo ?",
      ar: "ما حجم الصورة المسموح؟",
    },
    answer: {
      de: "Das Foto darf maximal 1 MB groß sein.",
      en: "The photo may be at most 1 MB in size.",
      fr: "La photo peut mesurer au maximum 1 Mo.",
      ar: "لا تتجاوز الصورة 1 ميغابايت.",
    },
    keywords: ["photo", "size", "1mb"],
  },
  {
    id: "cv-reorder",
    category: "cv-templates",
    question: {
      de: "Kann ich die Bereiche umordnen?",
      en: "Can I reorder the sections?",
      fr: "Puis-je réorganiser les sections ?",
      ar: "هل يمكنني إعادة ترتيب الأقسام؟",
    },
    answer: {
      de: "Ja. Sie können Einträge verschieben und neu ordnen, um die Reihenfolge Ihres CVs anzupassen.",
      en: "Yes. You can move and reorder entries to adjust the order of your CV.",
      fr: "Oui. Vous pouvez déplacer et réorganiser les entrées pour adapter l'ordre de votre CV.",
      ar: "نعم. يمكنك نقل المدخلات وإعادة ترتيبها لتعديل ترتيب سيرتك.",
    },
    keywords: ["reorder", "move", "order"],
  },
  {
    id: "cv-autosave",
    category: "cv-templates",
    question: {
      de: "Wird mein CV automatisch gespeichert?",
      en: "Is my CV automatically saved?",
      fr: "Mon CV est-il enregistré automatiquement ?",
      ar: "هل تُحفظ سيرتي تلقائيًا؟",
    },
    answer: {
      de: "Ja. Ihre Änderungen werden automatisch in Ihrem Browser (lokal, pro Nutzer) gespeichert, sobald Sie aufhören zu tippen.",
      en: "Yes. Your changes are automatically saved in your browser (locally, per user) as soon as you stop typing.",
      fr: "Oui. Vos modifications sont enregistrées automatiquement dans votre navigateur (localement, par utilisateur) dès que vous cessez de taper.",
      ar: "نعم. تُحفظ تعديلاتك تلقائيًا في متصفحك (محليًا، لكل مستخدم) بمجرد توقفك عن الكتابة.",
    },
    keywords: ["autosave", "local", "save"],
  },
  {
    id: "cv-after-refresh",
    category: "cv-templates",
    question: {
      de: "Was passiert nach einem Refresh?",
      en: "What happens after a refresh?",
      fr: "Que se passe-t-il après un rechargement ?",
      ar: "ماذا يحدث بعد إعادة التحميل؟",
    },
    answer: {
      de: "Ihr CV bleibt erhalten: Die lokal gespeicherten Angaben werden beim Neuladen automatisch wiederhergestellt.",
      en: "Your CV is kept: the locally saved details are automatically restored on reload.",
      fr: "Votre CV est conservé : les informations enregistrées localement sont automatiquement restaurées au rechargement.",
      ar: "تبقى سيرتك محفوظة: تُستعاد البيانات المحفوظة محليًا تلقائيًا عند إعادة التحميل.",
    },
    keywords: ["refresh", "restore", "persist"],
  },
  {
    id: "cv-import",
    category: "cv-templates",
    question: {
      de: "Kann ich mein Profil importieren?",
      en: "Can I import my profile?",
      fr: "Puis-je importer mon profil ?",
      ar: "هل يمكنني استيراد ملفي؟",
    },
    answer: {
      de: "Ja. Sie können Ihr letztes Profil aus dem Bewerbungsscan importieren, um die Bereiche automatisch zu befüllen.",
      en: "Yes. You can import your latest profile from the Application Scanner to auto-fill the sections.",
      fr: "Oui. Vous pouvez importer votre dernier profil du Scan de candidature pour préremplir automatiquement les sections.",
      ar: "نعم. يمكنك استيراد آخر ملف لك من ماسح الطلبات لملء الأقسام تلقائيًا.",
    },
    keywords: ["import", "profile", "scanner"],
  },
  {
    id: "cv-import-what",
    category: "cv-templates",
    question: {
      de: "Was wird beim Import übernommen?",
      en: "What is imported?",
      fr: "Qu'est-ce qui est importé ?",
      ar: "ما الذي يُستورد عند الاستيراد؟",
    },
    answer: {
      de: "Übernommen werden Name, Ort, E-Mail, Telefon und LinkedIn, die erste Zielfunktion als Titel, sowie Bildung, Erfahrung, Kenntnisse, Sprachen und Weiterbildung (als Zertifikate).",
      en: "Imported are name, location, email, phone and LinkedIn, the first target role as title, plus education, experience, skills, languages and training (as certificates).",
      fr: "Sont importés le nom, le lieu, l'e-mail, le téléphone et LinkedIn, la première fonction cible en titre, ainsi que la formation, l'expérience, les compétences, les langues et le perfectionnement (en certifications).",
      ar: "يُستورد الاسم والموقع والبريد والهاتف وLinkedIn، وأول وظيفة مستهدفة كعنوان، بالإضافة إلى التعليم والخبرة والمهارات واللغات والتدريب (كشهادات).",
    },
    keywords: ["import", "fields", "what"],
  },
  {
    id: "cv-import-no-invent",
    category: "cv-templates",
    question: {
      de: "Was wird beim Import nicht erfunden?",
      en: "What is not invented on import?",
      fr: "Qu'est-ce qui n'est pas inventé à l'import ?",
      ar: "ما الذي لا يُخترع عند الاستيراد؟",
    },
    answer: {
      de: "Zusammenfassung, Projekte und Interessen bleiben beim Import bewusst leer – die Plattform erfindet keinen Inhalt, den Sie nicht angeben.",
      en: "Summary, projects and interests are deliberately left empty on import – the platform invents no content you don't provide.",
      fr: "Le résumé, les projets et les centres d'intérêt restent volontairement vides à l'import – la plateforme n'invente aucun contenu que vous ne fournissez pas.",
      ar: "يبقى الملخص والمشاريع والهوايات فارغة عمدًا عند الاستيراد — فلا تخترع المنصّة محتوى لا تزوّدها به.",
    },
    keywords: ["no invent", "import", "empty"],
  },
  {
    id: "cv-pdf",
    category: "cv-templates",
    question: {
      de: "Wie lade ich mein CV als PDF herunter?",
      en: "How do I download my CV as PDF?",
      fr: "Comment télécharger mon CV en PDF ?",
      ar: "كيف أحمّل سيرتي كملف PDF؟",
    },
    answer: {
      de: "Klicken Sie auf den Button für den PDF-Download. Es öffnet sich die Druck-/Speichern-Ansicht, aus der Sie Ihr CV als PDF speichern können.",
      en: "Click the PDF download button. The print/save view opens, from which you can save your CV as PDF.",
      fr: "Cliquez sur le bouton de téléchargement PDF. La vue d'impression/sauvegarde s'ouvre, depuis laquelle vous pouvez enregistrer votre CV en PDF.",
      ar: "انقر على زر تنزيل PDF. ستُفتح واجهة الطباعة/الحفظ التي يمكنك من خلالها حفظ سيرتك كملف PDF.",
    },
    keywords: ["pdf", "download", "print"],
  },
  {
    id: "cv-pdf-preview",
    category: "cv-templates",
    question: {
      de: "Verwendet das PDF dieselbe Vorschau?",
      en: "Does the PDF use the same preview?",
      fr: "Le PDF utilise-t-il la même aperçu ?",
      ar: "هل يستخدم ملف PDF نفس المعاينة؟",
    },
    answer: {
      de: "Ja. Die PDF-Ansicht entspricht der Vorschau, die Sie im Builder sehen – was Sie sehen, ist, was Sie herunterladen.",
      en: "Yes. The PDF view matches the preview you see in the builder – what you see is what you download.",
      fr: "Oui. La vue PDF correspond à l'aperçu que vous voyez dans l'éditeur – ce que vous voyez est ce que vous téléchargez.",
      ar: "نعم. تتطابق واجهة PDF مع المعاينة التي تراها في الأداة — ما تراه هو ما تنزله.",
    },
    keywords: ["pdf", "preview", "same"],
  },
  {
    id: "cv-empty-section",
    category: "cv-templates",
    question: {
      de: "Was passiert, wenn ein Bereich leer ist?",
      en: "What happens if a section is empty?",
      fr: "Que se passe-t-il si une section est vide ?",
      ar: "ماذا يحدث إذا كان القسم فارغًا؟",
    },
    answer: {
      de: "Leere Bereiche werden nicht dargestellt – Ihr CV zeigt nur die Bereiche mit Inhalt. So bleibt der Aufbau sauber.",
      en: "Empty sections are not displayed – your CV shows only the sections with content. This keeps the layout clean.",
      fr: "Les sections vides ne sont pas affichées – votre CV ne montre que les sections avec du contenu. Ainsi, l'agencement reste propre.",
      ar: "لا تُعرض الأقسام الفارغة — فلا تعرض سيرتك إلا الأقسام التي لها محتوى. ليبقى التصميم نظيفًا.",
    },
    keywords: ["empty", "section", "hidden"],
  },
];
