import type { FaqItem } from "../types";

/** Category 1 — General / Allgemein */
export const generalItems: FaqItem[] = [
  {
    id: "general-what-is",
    category: "general",
    question: {
      de: "Was ist Ausbildung Hunter AI?",
      en: "What is Ausbildung Hunter AI?",
      fr: "Qu'est-ce qu'Ausbildung Hunter AI ?",
      ar: "ما هي Ausbildung Hunter AI؟",
    },
    answer: {
      de: "Ausbildung Hunter AI ist eine Plattform, die Ihnen hilft, Ausbildungs- und Arbeitsmöglichkeiten in Deutschland zu finden, zu bewerben und zu verwalten – mit Suche, KI-Hilfe und Bewerbungstools.",
      en: "Ausbildung Hunter AI is a platform that helps you find, apply to and manage apprenticeship and job opportunities in Germany – with search, AI help and application tools.",
      fr: "Ausbildung Hunter AI est une plateforme qui vous aide à trouver, candidater et gérer des formations et des offres d'emploi en Allemagne – avec recherche, aide IA et outils de candidature.",
      ar: "Ausbildung Hunter AI هي منصّة تساعدك على إيجاد فرص التدريب المهني والعمل في ألمانيا، والتقديم إليها وإدارتها — مع أدوات للبحث والمساعدة بالذكاء الاصطناعي وتقديم الطلبات.",
    },
    keywords: ["platform", "ausbildung", "jobs", "germany", "hunter"],
  },
  {
    id: "general-what-can-do",
    category: "general",
    question: {
      de: "Was kann ich mit der Plattform machen?",
      en: "What can I do with the platform?",
      fr: "Que puis-je faire avec la plateforme ?",
      ar: "ما الذي يمكنني فعله مع المنصّة؟",
    },
    answer: {
      de: "Sie können Stellen suchen und speichern, mit KI suchen, Bewerbungen erstellen und per E-Mail direkt versenden, Ihren Lebenslauf und Ihr Anschreiben erstellen, Bewerbungsunterlagen scannen und Ihre Nutzung verwalten.",
      en: "You can search for and save jobs, search with AI, create applications and send them directly by email, build your CV and cover letter, scan application documents and manage your usage.",
      fr: "Vous pouvez rechercher et enregistrer des offres, rechercher avec l'IA, créer des candidatures et les envoyer directement par e-mail, créer votre CV et votre lettre de motivation, scanner des documents et gérer votre utilisation.",
      ar: "يمكنك البحث عن الوظائف وحفظها، والبحث بالذكاء الاصطناعي، وإنشاء الطلبات وإرسالها مباشرةً عبر البريد، وبناء سيرتك الذاتية وخطاب التقديم، ومسح المستندات، وإدارة استخدامك.",
    },
    keywords: ["features", "search", "apply", "cv", "cover letter"],
  },
  {
    id: "general-who-for",
    category: "general",
    question: {
      de: "Für wen ist die Plattform gedacht?",
      en: "Who is the platform for?",
      fr: "À qui s'adresse la plateforme ?",
      ar: "لمن هذه المنصّة؟",
    },
    answer: {
      de: "Für alle, die in Deutschland eine Ausbildung oder einen Job suchen – auch wenn Sie noch keinen deutschen Lebenslauf haben.",
      en: "For anyone looking for an apprenticeship or a job in Germany – even if you don't have a German CV yet.",
      fr: "Pour toute personne qui cherche une formation ou un emploi en Allemagne – même sans CV allemand pour l'instant.",
      ar: "لجميع من يبحث عن تدريب مهني أو عمل في ألمانيا — حتى إذا لم تكن لديك سيرة ذاتية ألمانية بعد.",
    },
    keywords: ["target", "audience", "candidates"],
  },
  {
    id: "general-only-ausbildung",
    category: "general",
    question: {
      de: "Ist die Plattform nur für die Ausbildung?",
      en: "Is the platform only for apprenticeships?",
      fr: "La plateforme est-elle uniquement pour l'alternance ?",
      ar: "هل المنصّة مخصّصة للتدريب المهني فقط؟",
    },
    answer: {
      de: "Nein. Beim Start wählen Sie Ihr Ziel: Ausbildung oder Arbeit. Beide Ziele werden vollständig unterstützt.",
      en: "No. At the start you choose your goal: apprenticeship or job. Both goals are fully supported.",
      fr: "Non. Au départ vous choisissez votre objectif : alternance ou emploi. Les deux sont entièrement pris en charge.",
      ar: "لا. عند البدء تختار هدفك: التدريب المهني أو العمل. كلا الهدفين مدعومان بالكامل.",
    },
    keywords: ["ausbildung", "job", "goal"],
  },
  {
    id: "general-normal-jobs",
    category: "general",
    question: {
      de: "Kann ich auch normale Jobs suchen?",
      en: "Can I search for regular jobs?",
      fr: "Puis-je aussi chercher des emplois classiques ?",
      ar: "هل يمكنني البحث عن وظائف عادية؟",
    },
    answer: {
      de: "Ja. Bei der Suche können Sie das Ziel Arbeit wählen, um reguläre Stellen zu finden – die Suche deckt Ausbildung und Arbeit ab.",
      en: "Yes. In the search you can pick the goal Job to find regular positions – the search covers both apprenticeships and jobs.",
      fr: "Oui. Dans la recherche, choisissez l'objectif « Emploi » pour trouver des postes classiques – la recherche couvre alternance et emploi.",
      ar: "نعم. اختر في البحث هدف «العمل» لإيجاد وظائف عادية — البحث يغطي التدريب والعمل معًا.",
    },
    keywords: ["jobs", "arbeit", "regular"],
  },
  {
    id: "general-helps-apply",
    category: "general",
    question: {
      de: "Unterstützt die Plattform mich bei der Bewerbung?",
      en: "Does the platform help me apply for jobs?",
      fr: "La plateforme m'aide-t-elle à postuler ?",
      ar: "هل تساعدني المنصّة في تقديم الطلبات؟",
    },
    answer: {
      de: "Ja. Sie können Bewerbungen erstellen, aus einer Stellenanzeige vorausfüllen und sie über ein verknüpftes E-Mail-Konto (Gmail oder Outlook) direkt versenden.",
      en: "Yes. You can create applications, pre-fill them from a job listing and send them directly through a connected email account (Gmail or Outlook).",
      fr: "Oui. Vous pouvez créer des candidatures, les préremplir depuis une offre et les envoyer directement via un compte e-mail connecté (Gmail ou Outlook).",
      ar: "نعم. يمكنك إنشاء الطلبات، وملؤها تلقائيًا من إعلان الوظيفة، وإرسالها مباشرةً عبر حساب بريد مربوط (Gmail أو Outlook).",
    },
    keywords: ["apply", "bewerbung", "application"],
  },
  {
    id: "general-mobile",
    category: "general",
    question: {
      de: "Kann ich die Plattform mobil nutzen?",
      en: "Can I use the platform from mobile?",
      fr: "Puis-je utiliser la plateforme sur mobile ?",
      ar: "هل يمكنني استخدام المنصّة من الجوال؟",
    },
    answer: {
      de: "Ja, die Oberfläche ist voll responsiv und funktioniert auf Smartphone, Tablet und Desktop – inklusive RTL-Ansicht für Arabisch.",
      en: "Yes, the interface is fully responsive and works on smartphone, tablet and desktop – including an RTL view for Arabic.",
      fr: "Oui, l'interface est entièrement responsive et fonctionne sur smartphone, tablette et ordinateur – avec une vue RTL pour l'arabe.",
      ar: "نعم، الواجهة متجاوبة بالكامل وتعمل على الهاتف والحاسوب اللوحي وسطح المكتب — مع اتجاه RTL للعربية.",
    },
    keywords: ["mobile", "responsive", "tablet"],
  },
  {
    id: "general-languages",
    category: "general",
    question: {
      de: "Welche Sprachen werden unterstützt?",
      en: "Which languages are supported?",
      fr: "Quelles langues sont prises en charge ?",
      ar: "ما هي اللغات المدعومة؟",
    },
    answer: {
      de: "Deutsch, English, Français und العربية. Sie können die Sprache jederzeit in der Kopfzeile wechseln.",
      en: "Deutsch, English, Français and العربية. You can switch the language any time from the header.",
      fr: "Deutsch, English, Français et العربية. Vous pouvez changer de langue à tout moment depuis l'en-tête.",
      ar: "الألمانية والإنجليزية والفرنسية والعربية. يمكنك تبديل اللغة في أي وقت من الشريط العلوي.",
    },
    keywords: ["language", "deutsch", "english", "francais", "arabe"],
  },
  {
    id: "general-german",
    category: "general",
    question: {
      de: "Funktioniert die Plattform auf Deutsch?",
      en: "Does the platform work in German?",
      fr: "La plateforme fonctionne-t-elle en allemand ?",
      ar: "هل تعمل المنصّة بالألمانية؟",
    },
    answer: {
      de: "Ja, Deutsch ist die Standardsprache. Alle Inhalte, Tools und Texte sind auf Deutsch verfügbar und natürlich formuliert.",
      en: "Yes, German is the default language. All content, tools and text are available in German, phrased naturally.",
      fr: "Oui, l'allemand est la langue par défaut. Tout le contenu, les outils et les textes sont disponibles en allemand, formulés naturellement.",
      ar: "نعم، الألمانية هي اللغة الافتراضية. كل المحتوى والأدوات والنصوص متوفرة بألمانية طبيعية ومناسبة.",
    },
    keywords: ["german", "deutsch", "language"],
  },
  {
    id: "general-account-required",
    category: "general",
    question: {
      de: "Wird ein Konto benötigt?",
      en: "Is an account required?",
      fr: "Faut-il un compte ?",
      ar: "هل الحساب مطلوب؟",
    },
    answer: {
      de: "Ja. Für die Suche und alle Tools benötigen Sie ein bestätigtes Konto.",
      en: "Yes. You need a confirmed account to use the search and all tools.",
      fr: "Oui. Un compte confirmé est nécessaire pour utiliser la recherche et tous les outils.",
      ar: "نعم. تحتاج إلى حساب مُوثّق لاستخدام البحث وجميع الأدوات.",
    },
    keywords: ["account", "login", "required"],
  },
  {
    id: "general-create-account",
    category: "general",
    question: {
      de: "Wie erstelle ich ein Konto?",
      en: "How do I create an account?",
      fr: "Comment créer un compte ?",
      ar: "كيف أنشئ حسابًا؟",
    },
    answer: {
      de: "Klicken Sie auf 'Registrieren', geben Sie Name, E-Mail und ein Passwort (mindestens 8 Zeichen) an und bestätigen Sie anschließend Ihr Konto per E-Mail.",
      en: "Click 'Register', enter your name, email and a password (at least 8 characters), then confirm your account by email.",
      fr: "Cliquez sur « S'inscrire », saisissez votre nom, votre e-mail et un mot de passe (au moins 8 caractères), puis confirmez votre compte par e-mail.",
      ar: "اضغط على «تسجيل»، وأدخل الاسم والبريد وكلمة المرور (8 أحرف على الأقل)، ثم وثّق حسابك عبر البريد.",
    },
    keywords: ["register", "sign up", "create account"],
  },
  {
    id: "general-login",
    category: "general",
    question: {
      de: "Wie melde ich mich an?",
      en: "How do I log in?",
      fr: "Comment me connecter ?",
      ar: "كيف أسجّل الدخول؟",
    },
    answer: {
      de: "Auf der Anmeldeseite geben Sie Ihre E-Mail und Ihr Passwort ein und klicken Sie auf 'Anmelden'.",
      en: "On the sign-in page, enter your email and password and click 'Sign in'.",
      fr: "Sur la page de connexion, saisissez votre e-mail et votre mot de passe puis cliquez sur « Se connecter ».",
      ar: "في صفحة تسجيل الدخول أدخل بريدك وكلمة مرورك واضغط على «تسجيل الدخول».",
    },
    keywords: ["login", "sign in"],
  },
  {
    id: "general-cannot-login",
    category: "general",
    question: {
      de: "Was tun, wenn ich mich nicht anmelden kann?",
      en: "What should I do if I cannot log in?",
      fr: "Que faire si je ne peux pas me connecter ?",
      ar: "ماذا أفعل إذا تعذّر عليّ تسجيل الدخول؟",
    },
    answer: {
      de: "Prüfen Sie E-Mail, Passwort und Internetverbindung. Fehlt die Bestätigungs-E-Mail, senden Sie sie auf der Bestätigungsseite erneut. Bei weiterem Problem wenden Sie sich an den Plattform-Betreiber.",
      en: "Check your email, password and internet connection. If the confirmation email is missing, resend it on the verification page. If the problem persists, contact the platform owner.",
      fr: "Vérifiez votre e-mail, votre mot de passe et votre connexion. Si l'e-mail de confirmation manque, renvoyez-le depuis la page de vérification. Sinon, contactez le propriétaire de la plateforme.",
      ar: "تحقق من البريد وكلمة المرور واتصال الإنترنت. إذا كان بريد التأكيد مفقودًا، أعد إرساله من صفحة التوثيق. إن استمرت المشكلة، تواصل مع مالك المنصّة.",
    },
    keywords: ["login", "problem", "error", "verify"],
  },
  {
    id: "general-forgot-password",
    category: "general",
    question: {
      de: "Was passiert, wenn ich mein Passwort vergesse?",
      en: "What happens if I forget my password?",
      fr: "Que se passe-t-il si j'oublie mon mot de passe ?",
      ar: "ماذا يحدث إذا نسيت كلمة المرور؟",
    },
    answer: {
      de: "Eine automatische Passwort-Reset-Funktion ist derzeit nicht verfügbar. Bitte wenden Sie sich an den Plattform-Betreiber, um Ihr Passwort zurücksetzen zu lassen.",
      en: "An automatic password-reset feature is currently not available. Please contact the platform owner to have your password reset.",
      fr: "Une fonction de réinitialisation automatique du mot de passe n'est pas disponible pour le moment. Veuillez contacter le propriétaire de la plateforme.",
      ar: "إعادة تعيين كلمة المرور تلقائيًا غير متاحة حاليًا. تواصل مع مالك المنصّة لإعادة تعيينها.",
    },
    keywords: ["password", "forgot", "reset"],
  },
  {
    id: "general-logout-all",
    category: "general",
    question: {
      de: "Kann ich mich von allen Geräten abmelden?",
      en: "Can I log out from all devices?",
      fr: "Puis-je me déconnecter de tous les appareils ?",
      ar: "هل يمكنني تسجيل الخروج من جميع الأجهزة؟",
    },
    answer: {
      de: "Diese Funktion ist derzeit nicht verfügbar. Sie können sich nur auf dem aktuellen Gerät abmelden.",
      en: "This feature is currently not available. You can only sign out on the current device.",
      fr: "Cette fonction n'est pas disponible pour le moment. Vous ne pouvez vous déconnecter que sur l'appareil actuel.",
      ar: "هذه الوظيفة غير متاحة حاليًا. يمكنك تسجيل الخروج من الجهاز الحالي فقط.",
    },
    keywords: ["logout", "devices", "session"],
  },
];
