import type { FaqItem } from "../types";

/** Category 9 — Bewerbung Scanner / Bewerbungsscan */
export const scannerItems: FaqItem[] = [
  {
    id: "scan-what",
    category: "scanner",
    question: {
      de: "Was ist der Bewerbungsscan?",
      en: "What is the Application Scanner?",
      fr: "Qu'est-ce que le Scan de candidature ?",
      ar: "ما هو ماسح الطلبات؟",
    },
    answer: {
      de: "Der Bewerbungsscan liest Ihre Bewerbungsunterlagen (z. B. Ihren Lebenslauf) und extrahiert daraus Ihre Angaben – Ausbildung, Erfahrung, Skills, Sprachen und mehr – als geordnetes Profil.",
      en: "The Application Scanner reads your application documents (e.g. your CV) and extracts your details from them – education, experience, skills, languages and more – as an organized profile.",
      fr: "Le Scan de candidature lit vos documents (p. ex. votre CV) et en extrait vos informations – formation, expérience, compétences, langues, etc. – sous forme de profil organisé.",
      ar: "يقوم ماسح الطلبات بقراءة مستنداتك (مثل سيرتك الذاتية) ويستخرج منها بياناتك — التعليم والخبرة والمهارات واللغات وغيرها — كملف منظم.",
    },
    keywords: ["scanner", "what", "cv"],
  },
  {
    id: "scan-does",
    category: "scanner",
    question: {
      de: "Was macht der Bewerbungsscan?",
      en: "What does the scanner do?",
      fr: "Que fait le scan ?",
      ar: "ماذا يفعل الماسح؟",
    },
    answer: {
      de: "Er analysiert Ihre hochgeladenen Dokumente, stellt Ihre Angaben strukturiert zusammen und zeigt Ihnen, was fehlt oder wo Sie Nachschärfen können.",
      en: "It analyzes your uploaded documents, assembles your details in a structured way and shows you what is missing or where you can improve.",
      fr: "Il analyse vos documents téléversés, assemble vos informations de façon structurée et vous montre ce qui manque ou où vous pouvez améliorer.",
      ar: "يحلل المستندات المرفوعة ويركّب بياناتك بشكل منظم ويوضح لك ما ينقص أو أين يمكنك التحسين.",
    },
    keywords: ["does", "analyze", "structure"],
  },
  {
    id: "scan-upload",
    category: "scanner",
    question: {
      de: "Wie lade ich meinen Lebenslauf hoch?",
      en: "How do I upload my CV?",
      fr: "Comment téléverser mon CV ?",
      ar: "كيف أرفع سيرتي الذاتية؟",
    },
    answer: {
      de: "Öffnen Sie den Bewerbungsscan und laden Sie Ihre Dateien hoch. Sie können mehrere Dokumente auf einmal auswählen.",
      en: "Open the Application Scanner and upload your files. You can select several documents at once.",
      fr: "Ouvrez le Scan de candidature et téléversez vos fichiers. Vous pouvez sélectionner plusieurs documents à la fois.",
      ar: "افتح ماسح الطلبات وارفع ملفاتك. يمكنك اختيار عدة مستندات في وقت واحد.",
    },
    keywords: ["upload", "cv", "how"],
  },
  {
    id: "scan-formats",
    category: "scanner",
    question: {
      de: "Welche Dateitype werden akzeptiert?",
      en: "Which file types are accepted?",
      fr: "Quels types de fichiers sont acceptés ?",
      ar: "ما أنواع الملفات المقبولة؟",
    },
    answer: {
      de: "Akzeptiert werden PDF, DOC, DOCX, PNG, JPEG, WEBP und TXT. Die Datei wird anhand ihres tatsächlichen Inhalts geprüft; pro Datei gelten 10 MB.",
      en: "Accepted are PDF, DOC, DOCX, PNG, JPEG, WEBP and TXT. The file is checked by its actual content; 10 MB per file apply.",
      fr: "Sont acceptés PDF, DOC, DOCX, PNG, JPEG, WEBP et TXT. Le fichier est vérifié selon son contenu réel ; 10 Mo par fichier s'appliquent.",
      ar: "الأنواع المقبولة: PDF وDOC وDOCX وPNG وJPEG وWEBP وTXT. يُفحص الملف حسب محتواه الفعلي؛ والحد 10 ميغابايت لكل ملف.",
    },
    keywords: ["formats", "pdf", "doc", "accepted"],
  },
  {
    id: "scan-after-pdf",
    category: "scanner",
    question: {
      de: "Was passiert, nachdem ich ein PDF hochgeladen habe?",
      en: "What happens after I upload a PDF?",
      fr: "Que se passe-t-il après l'envoi d'un PDF ?",
      ar: "ماذا يحدث بعد رفع ملف PDF؟",
    },
    answer: {
      de: "Die Datei wird eingelesen und analysiert. Anschließend sehen Sie Ihr extrahiertes Profil mit den erkannten Angaben – Sie können Korrekturen vornehmen, die erhalten bleiben.",
      en: "The file is read and analyzed. Afterwards you see your extracted profile with the recognized details – you can make corrections, which are preserved.",
      fr: "Le fichier est lu et analysé. Ensuite, vous voyez votre profil extrait avec les détails reconnus – vous pouvez apporter des corrections, qui sont conservées.",
      ar: "يُقرأ الملف ويحلَّل. بعدها ترى ملفك المستخرج مع البيانات المعترف بها — ويمكنك إدخال تعديلات تبقى محفوظة.",
    },
    keywords: ["after", "pdf", "analyze"],
  },
  {
    id: "scan-german-cv",
    category: "scanner",
    question: {
      de: "Kann er einen deutschen Lebenslauf lesen?",
      en: "Can it read a German CV?",
      fr: "Peut-il lire un CV allemand ?",
      ar: "هل يمكنه قراءة سيرة ذاتية ألمانية؟",
    },
    answer: {
      de: "Ja. Der Scan ist darauf ausgelegt, deutsche Lebensläufe und Bewerbungen korrekt zu lesen und zu verstehen.",
      en: "Yes. The scan is designed to correctly read and understand German CVs and applications.",
      fr: "Oui. Le scan est conçu pour lire et comprendre correctement les CV et candidatures allemands.",
      ar: "نعم. صُمم الماسح لقراءة السير الذاتية الألمانية وطلبات التقديم وفهمها بشكل صحيح.",
    },
    keywords: ["german", "cv", "read"],
  },
  {
    id: "scan-umlauts",
    category: "scanner",
    question: {
      de: "Liest er Ä, Ö, Ü und ß korrekt?",
      en: "Does it correctly read Ä, Ö, Ü and ß?",
      fr: "Lit-il correctement Ä, Ö, Ü et ß ?",
      ar: "هل يقرأ الأحرف Ä وÖ وÜ وß بشكل صحيح؟",
    },
    answer: {
      de: "Ja. Deutsche Sonderzeichen wie Ä, Ö, Ü und ß werden beim Scan ausdrücklich erhalten und korrekt wiedergegeben.",
      en: "Yes. German special characters such as Ä, Ö, Ü and ß are explicitly preserved and rendered correctly during the scan.",
      fr: "Oui. Les caractères spéciaux allemands comme Ä, Ö, Ü et ß sont expressément conservés et affichés correctement lors du scan.",
      ar: "نعم. تُحفظ الأحرف الخاصة الألمانية مثل Ä وÖ وÜ وß بشكل صريح وتُعرض بشكل صحيح أثناء المسح.",
    },
    keywords: ["umlauts", "ä", "ö", "ü", "ß"],
  },
  {
    id: "scan-analyzes-what",
    category: "scanner",
    question: {
      de: "Welche Informationen analysiert der Scan?",
      en: "Which information does the scan analyze?",
      fr: "Quelles informations le scan analyse-t-il ?",
      ar: "ما المعلومات التي يحللها المسح؟",
    },
    answer: {
      de: "Kontakt, Ziel, Ausbildung, Weiterbildung, Erfahrung, Kenntnisse, Sprachen, Präferenzen, Zielfunktionen, Stärken, fehlende Informationen, mögliche Punkte und Keywords.",
      en: "Contact, goal, education, training, experience, skills, languages, preferences, target roles, strengths, missing information, potential points and keywords.",
      fr: "Contact, objectif, formation, perfectionnement, expérience, compétences, langues, préférences, fonctions cibles, points forts, informations manquantes, points potentiels et mots-clés.",
      ar: "التواصل، الهدف، التعليم، التدريب، الخبرة، المهارات، اللغات، التفضيلات، الوظائف المستهدفة، النقاط القوية، المعلومات المفقودة، النقاط المحتملة، والكلمات المفتاحية.",
    },
    keywords: ["analyzes", "info", "fields"],
  },
  {
    id: "scan-education",
    category: "scanner",
    question: {
      de: "Erkennt er meine Ausbildung?",
      en: "Does it recognize my education?",
      fr: "Reconnaît-il ma formation ?",
      ar: "هل يعترف بتعليمي؟",
    },
    answer: {
      de: "Ja. Der Scan erfasst Ihre Ausbildungs- und Bildungsabschlüsse und stellt sie in Ihrem Profil dar.",
      en: "Yes. The scan captures your education and qualifications and shows them in your profile.",
      fr: "Oui. Le scan enregistre votre formation et vos qualifications et les affiche dans votre profil.",
      ar: "نعم. يلتقط المسح تعليمك وشهاداتك ويعرضها في ملفك.",
    },
    keywords: ["education", "training", "recognize"],
  },
  {
    id: "scan-experience",
    category: "scanner",
    question: {
      de: "Erkennt er meine Erfahrung?",
      en: "Does it recognize my experience?",
      fr: "Reconnaît-il mon expérience ?",
      ar: "هل يعترف بخبرتي؟",
    },
    answer: {
      de: "Ja. Berufserfahrung und Praktika werden erkannt und strukturiert in Ihr Profil übernommen.",
      en: "Yes. Work experience and internships are recognized and structured into your profile.",
      fr: "Oui. L'expérience professionnelle et les stages sont reconnus et structurés dans votre profil.",
      ar: "نعم. تُعترف بخبرات العمل والتدريب العملي وتُنظَّم في ملفك.",
    },
    keywords: ["experience", "work", "recognize"],
  },
  {
    id: "scan-skills-langs",
    category: "scanner",
    question: {
      de: "Erkennt er meine Skills und Sprachen?",
      en: "Does it recognize my skills and languages?",
      fr: "Reconnaît-il mes compétences et langues ?",
      ar: "هل يعترف بمهاراتي ولغاتي؟",
    },
    answer: {
      de: "Ja. Kenntnisse und Sprachkenntnisse werden mit ihren Stufen (soweit angegeben) erkannt und in Ihrem Profil aufgeführt.",
      en: "Yes. Skills and language skills are recognized with their levels (where stated) and listed in your profile.",
      fr: "Oui. Les compétences et les langues sont reconnues avec leurs niveaux (le cas échéant) et listées dans votre profil.",
      ar: "نعم. تُعترف بالمهارات واللغات مع مستوياتها (إذا ذُكرت) وتُدرج في ملفك.",
    },
    keywords: ["skills", "languages", "recognize"],
  },
  {
    id: "scan-training-goal",
    category: "scanner",
    question: {
      de: "Erkennt er meine Weiterbildung und mein Berufsziel?",
      en: "Does it recognize my further training and career goal?",
      fr: "Reconnaît-il ma formation continue et mon objectif professionnel ?",
      ar: "هل يعترف بتدريبتي الإضافي وهدفي المهني؟",
    },
    answer: {
      de: "Ja. Weiterbildung und Ihr Ziel (z. B. Ausbildung oder bestimmte Zielfunktionen) werden erkannt und in Ihr Profil übernommen.",
      en: "Yes. Further training and your goal (e.g. apprenticeship or specific target roles) are recognized and added to your profile.",
      fr: "Oui. La formation continue et votre objectif (p. ex. alternance ou fonctions cibles) sont reconnus et ajoutés à votre profil.",
      ar: "نعم. يُعترف بالتدريب الإضافي وهدفك (مثل التدريب المهني أو وظائف مستهدفة) ويضاف إلى ملفك.",
    },
    keywords: ["training", "goal", "target roles"],
  },
  {
    id: "scan-contact",
    category: "scanner",
    question: {
      de: "Kann er meine Kontaktdaten übernehmen?",
      en: "Can it pick up my contact details?",
      fr: "Peut-il reprendre mes coordonnées ?",
      ar: "هل يمكنه استلام بيانات تواصلتي؟",
    },
    answer: {
      de: "Ja. Name, E-Mail und Telefon werden, soweit in den Dokumenten enthalten, erkannt und als Kontaktdaten angezeigt.",
      en: "Yes. Name, email and phone, where present in the documents, are recognized and shown as contact details.",
      fr: "Oui. Le nom, l'e-mail et le téléphone, s'ils figurent dans les documents, sont reconnus et affichés comme coordonnées.",
      ar: "نعم. الاسم والبريد والهاتف، إذا وردت في المستندات، تُعترف وتُعرض كبيانات تواصل.",
    },
    keywords: ["contact", "name", "email", "phone"],
  },
  {
    id: "scan-invent",
    category: "scanner",
    question: {
      de: "Erfindet der Scan Informationen?",
      en: "Does the scan invent information?",
      fr: "Le scan invente-t-il des informations ?",
      ar: "هل يخترع المسح معلومات؟",
    },
    answer: {
      de: "Nein. Der Scan extrahiert nur Angaben, die in Ihren Dokumenten nachweisbar sind. Fehlende Informationen werden als fehlend markiert, nicht erfunden.",
      en: "No. The scan only extracts details that are demonstrably in your documents. Missing information is marked as missing, not invented.",
      fr: "Non. Le scan n'extrait que des informations démontrables dans vos documents. Les informations manquantes sont marquées comme manquantes, pas inventées.",
      ar: "لا. يستخرج المسح فقط البيانات المدعومة في مستنداتك. وتُعلَّم المعلومات المفقودة كمفقودة ولا تُخترع.",
    },
    keywords: ["invent", "no", "extract"],
  },
  {
    id: "scan-sparse",
    category: "scanner",
    question: {
      de: "Was tun, wenn die Analyse unvollständig ist?",
      en: "What to do if the analysis is incomplete?",
      fr: "Que faire si l'analyse est incomplète ?",
      ar: "ماذا أفعل إذا كان التحليل ناقصًا؟",
    },
    answer: {
      de: "Überprüfen Sie Ihre Dokumente und laden Sie sie notfalls erneut hoch oder ergänzen Sie die Angaben. Der Scan zeigt klar, welche Informationen fehlen, damit Sie sie ergänzen können.",
      en: "Check your documents and, if needed, re-upload them or add the missing details. The scan clearly shows which information is missing so you can complete it.",
      fr: "Vérifiez vos documents et, le cas échéant, renvoyez-les ou complétez les informations manquantes. Le scan montre clairement ce qui manque pour que vous le complétiez.",
      ar: "تحقق من مستنداتك وأعد رفعها عند الحاجة أو أكمل البيانات الناقصة. يوضح المسح ما ينقص لتتمكن من إكماله.",
    },
    keywords: ["incomplete", "sparse", "missing"],
  },
  {
    id: "scan-why-different",
    category: "scanner",
    question: {
      de: "Warum kann sich die Analyse unterscheiden?",
      en: "Why can the analysis differ?",
      fr: "Pourquoi l'analyse peut-elle différer ?",
      ar: "لماذا قد يختلف التحليل؟",
    },
    answer: {
      de: "Je nach Qualität, Struktur und Klarheit der Dokumente kann die Erkennung variieren. Ein klarer, gut strukturierter Lebenslauf liefert zuverlässigere Ergebnisse.",
      en: "Depending on the quality, structure and clarity of the documents, recognition can vary. A clear, well-structured CV yields more reliable results.",
      fr: "Selon la qualité, la structure et la clarté des documents, la reconnaissance peut varier. Un CV clair et bien structuré donne des résultats plus fiables.",
      ar: "حسب جودة المستندات وهيكلها ووضوحها، قد تختلف عملية التعرّف. فالسيرة الواضحة والمنظمة تعطي نتائج أكثر موثوقية.",
    },
    keywords: ["different", "vary", "quality"],
  },
  {
    id: "scan-invalid-pdf",
    category: "scanner",
    question: {
      de: "Was passiert, wenn das PDF ungültig ist?",
      en: "What happens if the PDF is invalid?",
      fr: "Que se passe-t-il si le PDF est invalide ?",
      ar: "ماذا يحدث إذا كان ملف PDF غير صالح؟",
    },
    answer: {
      de: "Dann zeigt die Plattform eine verständliche Meldung, dass das Dokument nicht gelesen werden konnte. Laden Sie eine gültige Datei erneut hoch.",
      en: "Then the platform shows a clear message that the document could not be read. Re-upload a valid file.",
      fr: "Alors la plateforme affiche un message clair que le document n'a pas pu être lu. Renvoyez un fichier valide.",
      ar: "في هذه الحالة تعرض المنصّة رسالة واضحة أن المستند لم يمكن قراءته. أعد رفع ملف صالح.",
    },
    keywords: ["invalid", "pdf", "error"],
  },
  {
    id: "scan-fail",
    category: "scanner",
    question: {
      de: "Was passiert, wenn die Analyse fehlschlägt?",
      en: "What happens if the analysis fails?",
      fr: "Que se passe-t-il si l'analyse échoue ?",
      ar: "ماذا يحدث إذا فشل التحليل؟",
    },
    answer: {
      de: "Dann wird der Scan als fehlgeschlagen markiert und Sie sehen eine nutzerfreundliche Fehlermeldung. Sie können die Dokumente erneut einreichen.",
      en: "Then the scan is marked as failed and you see a user-friendly error message. You can resubmit the documents.",
      fr: "Alors le scan est marqué comme échoué et vous voyez un message d'erreur convivial. Vous pouvez renvoyer les documents.",
      ar: "في هذه الحالة يُعلَّم المسح كفاشل وترى رسالة خطأ سهلة الفهم. يمكنك إعادة تقديم المستندات.",
    },
    keywords: ["fail", "error", "resubmit"],
  },
  {
    id: "scan-stored",
    category: "scanner",
    question: {
      de: "Bleibt meine Datei gespeichert?",
      en: "Is my file kept stored?",
      fr: "Mon fichier est-il conservé ?",
      ar: "هل يبقى ملفي محفوظًا؟",
    },
    answer: {
      de: "Ja. Ihre hochgeladenen Dokumente und die Scan-Ergebnisse werden in Ihrem Konto gespeichert und stehen in Ihrem Scan-Verlauf bereit.",
      en: "Yes. Your uploaded documents and scan results are stored in your account and are available in your scan history.",
      fr: "Oui. Vos documents téléversés et les résultats de scan sont stockés dans votre compte et disponibles dans votre historique de scans.",
      ar: "نعم. تُحفظ المستندات المرفوعة ونتائج المسح في حسابك وتكون متاحة في سجل المسح.",
    },
    keywords: ["stored", "history", "keep"],
  },
  {
    id: "scan-private",
    category: "scanner",
    question: {
      de: "Sind die Daten nur für mein Konto?",
      en: "Are the data only for my account?",
      fr: "Les données sont-elles seulement pour mon compte ?",
      ar: "هل البيانات لحسابي فقط؟",
    },
    answer: {
      de: "Ja. Gescannte Dokumente und Profile sind an Ihr Konto geknüpft und für Sie privat.",
      en: "Yes. Scanned documents and profiles are bound to your account and are private to you.",
      fr: "Oui. Les documents scannés et les profils sont liés à votre compte et privés pour vous.",
      ar: "نعم. المستندات الممسوحة والملفات مرتبطة بحسابك وخاصة بك.",
    },
    keywords: ["private", "account", "isolated"],
  },
  {
    id: "scan-bulk",
    category: "scanner",
    question: {
      de: "Wie viele Dateien kann ich auf einmal scannen?",
      en: "How many files can I scan at once?",
      fr: "Combien de fichiers puis-je scanner à la fois ?",
      ar: "كم ملفًا يمكنني مسحه في وقت واحد؟",
    },
    answer: {
      de: "Pro Scan können Sie bis zu 10 Dateien hochladen. So können Sie Lebenslauf, Anschreiben und Nachweise gemeinsam analysieren lassen.",
      en: "Per scan you can upload up to 10 files. This lets you have your CV, cover letter and certificates analyzed together.",
      fr: "Par scan, vous pouvez téléverser jusqu'à 10 fichiers. Vous pouvez ainsi faire analyser ensemble votre CV, votre lettre et vos attestations.",
      ar: "يمكنك رفع حتى 10 ملفات في كل مسح. هكذا يمكنك تحليل سيرتك وخطاب التقديم وشهاداتك معًا.",
    },
    keywords: ["bulk", "count", "10"],
  },
];
