import type { FaqItem } from "../types";

/** Category 3 — Ausbildung Search / Ausbildungssuche */
export const searchItems: FaqItem[] = [
  {
    id: "search-how",
    category: "search",
    question: {
      de: "Wie suche ich eine Ausbildung?",
      en: "How do I search for an apprenticeship?",
      fr: "Comment chercher une alternance ?",
      ar: "كيف أبحث عن تدريب مهني؟",
    },
    answer: {
      de: "Öffnen Sie die Stellenangebote, wählen Sie das Ziel Ausbildung und geben Sie Stichwort, Rolle oder Ort ein. Sie können die Ergebnisse zusätzlich nach Radius, Aktualität und weiteren Filtern eingrenzen.",
      en: "Open Opportunities, select the goal Apprenticeship and enter a keyword, role or location. You can further narrow results by radius, freshness and other filters.",
      fr: "Ouvrez les Offres, choisissez l'objectif Alternance et saisissez un mot-clé, une fonction ou un lieu. Vous pouvez affiner par rayon, fraîcheur et autres filtres.",
      ar: "افتح الوظائف المتاحة، واختر هدف التدريب، وأدخل كلمة مفتاحية أو وظيفة أو موقعًا. ويمكنك تضييق النتائج عبر النطاق الزمني والمنطقة وغيرها من عوامل التصفية.",
    },
    keywords: ["search", "ausbildung", "find"],
  },
  {
    id: "search-how-job",
    category: "search",
    question: {
      de: "Wie suche ich einen Job?",
      en: "How do I search for a job?",
      fr: "Comment chercher un emploi ?",
      ar: "كيف أبحث عن وظيفة؟",
    },
    answer: {
      de: "Wie bei der Ausbildung: Wählen Sie das Ziel Arbeit, geben Sie Ihre Suchbegriffe ein und nutzen Sie die Filter. Die Suche deckt sowohl Ausbildung als auch reguläre Stellen ab.",
      en: "Just like for apprenticeships: select the goal Job, enter your terms and use the filters. The search covers both apprenticeships and regular positions.",
      fr: "Comme pour l'alternance : choisissez l'objectif Emploi, saisissez vos termes et utilisez les filtres. La recherche couvre alternance et postes classiques.",
      ar: "كما في البحث عن التدريب: اختر هدف العمل وأدخل كلماتك واستخدم عوامل التصفية. البحث يغطي التدريب والوظائف العادية.",
    },
    keywords: ["search", "job", "arbeit"],
  },
  {
    id: "search-sources",
    category: "search",
    question: {
      de: "Woher kommen die Suchergebnisse?",
      en: "Where do the search results come from?",
      fr: "D'où proviennent les résultats de recherche ?",
      ar: "من أين تأتي نتائج البحث؟",
    },
    answer: {
      de: "Die klassische Suche nutzt eine einzige Quelle: die Jobbörse der Bundesagentur für Arbeit. Für breitere Ergebnisse steht die KI-Suche zur Verfügung, die zusätzlich Webquellen auswertet.",
      en: "The classic search uses a single source: the Federal Employment Agency's (Bundesagentur für Arbeit) Jobbörse. For broader results, the AI Search additionally evaluates web sources.",
      fr: "La recherche classique utilise une seule source : la Jobbörse de l'Agence fédérale pour l'emploi (Bundesagentur für Arbeit). Pour plus de résultats, la Recherche IA évalue en plus des sources web.",
      ar: "يعتمد البحث العادي على مصدر واحد: لوحة وظائف وكالة العمل الاتحادية (Bundesagentur für Arbeit). وللحصول على نتائج أوسع، يبحث البحث بالذكاء الاصطناعي أيضًا في مصادر الويب.",
    },
    keywords: ["source", "bundesagentur", "jobbörse"],
  },
  {
    id: "search-why-different",
    category: "search",
    question: {
      de: "Warum unterscheiden sich die Ergebnisse?",
      en: "Why do the results differ?",
      fr: "Pourquoi les résultats diffèrent-ils ?",
      ar: "لماذا تختلف النتائج؟",
    },
    answer: {
      de: "Die Jobbörse ändert sich laufend – Angebote werden hoch- und ausgeschrieben, neue erscheinen. Auch Ihre Filter und Suchbegriffe beeinflussen, was Sie sehen.",
      en: "The Jobbörse changes continuously – listings are added and withdrawn, new ones appear. Your filters and search terms also shape what you see.",
      fr: "La Jobbörse évolue en continu – des offres sont ajoutées et retirées, de nouvelles apparaissent. Vos filtres et termes de recherche influencent aussi ce que vous voyez.",
      ar: "تتغيّر لوحة الوظائف باستمرار — تُضاف إعلانات وتُسحب أخرى. كما تؤثر عوامل التصفية وكلمات البحث على ما تراه.",
    },
    keywords: ["results", "different", "change"],
  },
  {
    id: "search-no-results",
    category: "search",
    question: {
      de: "Warum werden manchmal keine Ergebnisse angezeigt?",
      en: "Why are there sometimes no results?",
      fr: "Pourquoi n'y a-t-il parfois aucun résultat ?",
      ar: "لماذا لا تظهر نتائج في بعض الأحيان؟",
    },
    answer: {
      de: "Das kann an zu engen Filtern oder Suchbegriffen liegen. Entfernen Sie Filter, erweitern Sie den Radius oder verwenden Sie allgemeinere Begriffe.",
      en: "This can be caused by filters or search terms that are too narrow. Remove filters, widen the radius or use more general terms.",
      fr: "Cela peut être dû à des filtres ou termes trop restrictifs. Retirez des filtres, élargissez le rayon ou utilisez des termes plus généraux.",
      ar: "قد يكون السبب عوامل تصفية أو كلمات ضيقة جدًا. أزل بعض عوامل التصفية، أو وسّع النطاق، أو استخدم كلمات أعم.",
    },
    keywords: ["no results", "empty", "filters"],
  },
  {
    id: "search-email-why",
    category: "search",
    question: {
      de: "Warum haben einige Ergebnisse eine E-Mail und andere nicht?",
      en: "Why do some results have an email and others not?",
      fr: "Pourquoi certains résultats ont un e-mail et d'autres non ?",
      ar: "لماذا تحتوي بعض النتائج على بريد إلكتروني وأخرى لا؟",
    },
    answer: {
      de: "Eine E-Mail wird nur angezeigt, wenn sie im Text des Originalangebots tatsächlich enthalten ist. Viele Unternehmen veröffentlichen keinen direkten Kontakt – dann gibt es keine E-Mail.",
      en: "An email is only shown when it is actually contained in the original listing's text. Many companies don't publish a direct contact – in that case there is no email.",
      fr: "Un e-mail n'est affiché que s'il figure réellement dans le texte de l'offre originale. Beaucoup d'entreprises ne publient pas de contact direct – il n'y a alors pas d'e-mail.",
      ar: "يظهر البريد الإلكتروني فقط إذا كان موجودًا فعلًا في نص الإعلان الأصلي. كثير من الشركات لا تنشر جهة تواصل مباشرة، وبالتالي لا يوجد بريد.",
    },
    keywords: ["email", "missing", "contact"],
  },
  {
    id: "search-email-invented",
    category: "search",
    question: {
      de: "Erfindet die Plattform E-Mail-Adressen?",
      en: "Does the platform invent email addresses?",
      fr: "La plateforme invente-t-elle des adresses e-mail ?",
      ar: "هل تخترع المنصّة عناوين البريد الإلكتروني؟",
    },
    answer: {
      de: "Nein. Die Plattform erfindet, rät oder leitet keine E-Mail-Adressen ab. Es werden nur Adressen übernommen, die im Angebots-Text vorkommen und formal gültig sind.",
      en: "No. The platform never invents, guesses or derives email addresses. It only keeps addresses that appear in the listing text and are formally valid.",
      fr: "Non. La plateforme n'invente, ne devine et ne déduit aucune adresse e-mail. Seules les adresses présentes dans le texte de l'offre et formellement valides sont conservées.",
      ar: "لا. لا تخترع المنصّة ولا تتخمن ولا تستنتج عناوين بريد. فقط العناوين الموجودة في نص الإعلان وصحيحة الصيغة هي ما يُعتمد.",
    },
    keywords: ["email", "invented", "guessed", "valid"],
  },
  {
    id: "search-source-link",
    category: "search",
    question: {
      de: "Wie erkenne ich die Quelle eines Angebots?",
      en: "How do I see the source of a listing?",
      fr: "Comment voir la source d'une offre ?",
      ar: "كيف أعرف مصدر الإعلان؟",
    },
    answer: {
      de: "Jedes Ergebnis zeigt seinen Quellentyp an. Über den Link zum Originalangebot öffnen Sie die ursprüngliche Quelle.",
      en: "Each result shows its source type. Via the link to the original listing you open the original source.",
      fr: "Chaque résultat indique son type de source. Via le lien vers l'offre originale, vous ouvrez la source d'origine.",
      ar: "تعرض كل نتيجة نوع مصدرها. ومن خلال الرابط إلى الإعلان الأصلي تفتح المصدر الأصلي.",
    },
    keywords: ["source", "type", "link"],
  },
  {
    id: "search-open-original",
    category: "search",
    question: {
      de: "Wie öffne ich das Originalangebot?",
      en: "How do I open the original listing?",
      fr: "Comment ouvrir l'offre originale ?",
      ar: "كيف أفتح الإعلان الأصلي؟",
    },
    answer: {
      de: "Klicken Sie im Ergebnis oder auf der Detailseite auf den Link zum Originalangebot. Es öffnet sich die ursprüngliche Quelle in einem neuen Tab.",
      en: "Click the link to the original listing in the result or on the detail page. The original source opens in a new tab.",
      fr: "Cliquez sur le lien vers l'offre originale dans le résultat ou sur la page de détail. La source d'origine s'ouvre dans un nouvel onglet.",
      ar: "انقر على الرابط إلى الإعلان الأصلي من النتيجة أو من صفحة التفاصيل. سيفتح المصدر الأصلي في تبويب جديد.",
    },
    keywords: ["original", "open", "link"],
  },
  {
    id: "search-save",
    category: "search",
    question: {
      de: "Wie speichere ich eine Stelle?",
      en: "How do I save a job?",
      fr: "Comment enregistrer une offre ?",
      ar: "كيف أحفظ وظيفة؟",
    },
    answer: {
      de: "Klicken Sie auf das Lesezeichen-Symbol beim Ergebnis. Die Stelle wird in Ihrem Konto unter Gespeicherte Stellen gespeichert.",
      en: "Click the bookmark icon on the result. The job is saved to your account under Saved Opportunities.",
      fr: "Cliquez sur l'icône signet sur le résultat. L'offre est enregistrée dans votre compte sous Offres enregistrées.",
      ar: "انقر على أيقونة الإحفظ في النتيجة. تُحفظ الوظيفة في حسابك ضمن الوظائف المحفوظة.",
    },
    keywords: ["save", "bookmark", "stored"],
  },
  {
    id: "search-delete-saved",
    category: "search",
    question: {
      de: "Wie lösche ich eine gespeicherte Stelle?",
      en: "How do I delete a saved job?",
      fr: "Comment supprimer une offre enregistrée ?",
      ar: "كيف أحذف وظيفة محفوظة؟",
    },
    answer: {
      de: "Öffnen Sie Gespeicherte Stellen und entfernen Sie die dort gewünschte Stelle. Sie wird aus Ihrer Liste gelöscht.",
      en: "Open Saved Opportunities and remove the job you want there. It is deleted from your list.",
      fr: "Ouvrez Offres enregistrées et supprimez l'offre voulue. Elle est supprimée de votre liste.",
      ar: "افتح الوظائف المحفوظة واحذف الوظيفة المطلوبة. ستُحذف من قائمتك.",
    },
    keywords: ["delete", "saved", "remove"],
  },
  {
    id: "search-ba-unavailable",
    category: "search",
    question: {
      de: "Was passiert, wenn die Bundesagentur für Arbeit nicht erreichbar ist?",
      en: "What happens if the Federal Employment Agency is not reachable?",
      fr: "Que se passe-t-il si l'Agence fédérale pour l'emploi est injoignable ?",
      ar: "ماذا يحدث إذا تعذّر الوصول إلى وكالة العمل الاتحادية؟",
    },
    answer: {
      de: "Die Suche meldet den Zustand der Quelle. Bei einer vorübergehenden Störung werden ggf. zwischengespeicherte oder teilweise Ergebnisse angezeigt; andernfalls zeigt die Plattform einen klaren Fehler mit der Option zum erneuten Versuch.",
      en: "The search reports the source's status. On a temporary outage it may show cached or partial results; otherwise the platform shows a clear error with a retry option.",
      fr: "La recherche signale l'état de la source. En cas de panne temporaire, des résultats mis en cache ou partiels peuvent s'afficher ; sinon, la plateforme montre une erreur claire avec l'option de réessayer.",
      ar: "يُبلغ البحث عن حالة المصدر. عند عطل مؤقت قد تظهر نتائج مخزّنة أو جزئية؛ وإلا تعرض المنصّة خطأً واضحًا مع خيار إعادة المحاولة.",
    },
    keywords: ["bundesagentur", "unavailable", "error"],
  },
  {
    id: "search-ba-message",
    category: "search",
    question: {
      de: "Warum erscheint die Meldung, dass die Bundesagentur für Arbeit nicht verfügbar ist?",
      en: "Why does it say the Federal Employment Agency is unavailable?",
      fr: "Pourquoi indique-t-il que l'Agence fédérale est indisponible ?",
      ar: "لماذا تظهر رسالة أن وكالة العمل غير متاحة؟",
    },
    answer: {
      de: "Das kann passieren, wenn die Jobbörse gerade überlastet ist oder kurz nicht antwortet. Warten Sie kurz und versuchen Sie es erneut – meist ist es ein vorübergehendes Problem.",
      en: "This can happen when the Jobbörse is temporarily overloaded or not responding. Wait a moment and try again – it is usually a transient issue.",
      fr: "Cela peut arriver quand la Jobbörse est temporairement surchargée ou ne répond pas. Attendez un instant et réessayez – c'est généralement un problème transitoire.",
      ar: "قد يحدث ذلك عندما تكون لوحة الوظائف مثقلة مؤقتًا أو لا تستجيب. انتظر قليلًا ثم أعد المحاولة — غالبًا هو عارض.",
    },
    keywords: ["bundesagentur", "unavailable", "message"],
  },
  {
    id: "search-missing-means",
    category: "search",
    question: {
      de: "Bedeutet eine fehlende Stelle, dass der Job nicht existiert?",
      en: "Does a missing job mean it doesn't exist?",
      fr: "Une offre manquante signifie-t-elle que le poste n'existe pas ?",
      ar: "هل يعني غياب الوظيفة أنها غير موجودة؟",
    },
    answer: {
      de: "Nein. Fehlt eine Stelle in den Ergebnissen, kann sie bereits ausgeschrieben sein, andere Filter nicht erfüllen oder gerade nicht geladen sein. Es bedeutet nicht automatisch, dass der Job nicht existiert.",
      en: "No. If a job is missing from the results, it may already be withdrawn, not meet your filters, or not loaded at that moment. It does not automatically mean the job doesn't exist.",
      fr: "Non. Si une offre manque, elle peut déjà être retirée, ne pas correspondre à vos filtres ou ne pas avoir été chargée. Cela ne signifie pas automatiquement que le poste n'existe pas.",
      ar: "لا. إذا غابت وظيفة عن النتائج فقد تكون أُغلقت، أو لا تتوافق مع عوامل التصفية، أو لم تُحمَّل في تلك اللحظة. لا يعني ذلك تلقائيًا أنها غير موجودة.",
    },
    keywords: ["missing", "exists", "withdrawn"],
  },
  {
    id: "search-same-results",
    category: "search",
    question: {
      de: "Liefert die Suche immer dieselben Ergebnisse?",
      en: "Does the search always return the same results?",
      fr: "La recherche renvoie-t-elle toujours les mêmes résultats ?",
      ar: "هل يعيد البحث دائمًا نفس النتائج؟",
    },
    answer: {
      de: "Nein. Die verfügbaren Angebote ändern sich laufend, daher können sich die Ergebnisse zwischen Suchen unterscheiden – selbst bei gleichem Suchbegriff.",
      en: "No. The available listings change continuously, so results can differ between searches – even with the same query.",
      fr: "Non. Les offres disponibles évoluent en continu, les résultats peuvent donc varier d'une recherche à l'autre – même avec le même terme.",
      ar: "لا. تتغيّر الإعلانات المتاحة باستمرار، لذا قد تختلف النتائج من بحث لآخر — حتى مع نفس الكلمات.",
    },
    keywords: ["same", "results", "repeat"],
  },
  {
    id: "search-results-change",
    category: "search",
    question: {
      de: "Warum können sich die Ergebnisse ändern?",
      en: "Why can the results change?",
      fr: "Pourquoi les résultats peuvent-ils changer ?",
      ar: "لماذا قد تتغيّر النتائج؟",
    },
    answer: {
      de: "Angebote werden neu veröffentlicht und ausgeschrieben, Quellen werden aktualisiert und Ihre Filter wirken. Kurze Zwischenspeicher können zudem für kurze Zeit frühere Daten zeigen.",
      en: "Listings are newly published and withdrawn, sources get updated, and your filters apply. Short caches can also briefly show earlier data.",
      fr: "Des offres sont publiées et retirées, les sources sont mises à jour et vos filtres s'appliquent. De courts caches peuvent aussi montrer brièvement des données antérieures.",
      ar: "تُنشر إعلانات جديدة وتُغلق أخرى، وتُحدَّث المصادر، وتعمل عوامل التصفية. كما قد تُظهر ذاكرة التخزين المؤقتة المؤقتة بيانات أقصر مدة.",
    },
    keywords: ["change", "results", "cache"],
  },
  {
    id: "search-retry",
    category: "search",
    question: {
      de: "Was tun, wenn die Suche fehlschlägt – und wann den erneuten Versuch nutzen?",
      en: "What to do if the search fails – and when to use retry?",
      fr: "Que faire si la recherche échoue – et quand utiliser le nouvel essai ?",
      ar: "ماذا أفعل إذا فشل البحث — ومتى أستخدم إعادة المحاولة؟",
    },
    answer: {
      de: "Bei einem Fehler prüfen Sie kurz Ihre Verbindung und klicken Sie auf erneuten Versuch. Nutzen Sie Retry, wenn die Quelle vorübergehend nicht erreichbar war oder die Suche abgebrochen wurde.",
      en: "On an error, briefly check your connection and click retry. Use Retry when the source was temporarily unreachable or the search was interrupted.",
      fr: "En cas d'erreur, vérifiez brièvement votre connexion et cliquez sur réessayer. Utilisez Retry quand la source était temporairement injoignable ou que la recherche a été interrompue.",
      ar: "عند حدوث خطأ، تحقق من اتصالك ثم انقر إعادة المحاولة. استخدم إعادة المحاولة عندما يكون المصدر غير متاح مؤقتًا أو انقطع البحث.",
    },
    keywords: ["retry", "error", "fail"],
  },
];
