import type { FaqItem } from "../types";

/** Category 18 — Technical Problems / Technische Probleme */
export const technicalItems: FaqItem[] = [
  {
    id: "tp-page",
    category: "technical",
    question: {
      de: "Warum öffnet sich die Seite nicht?",
      en: "Why doesn't the page open?",
      fr: "Pourquoi la page ne s'ouvre-t-elle pas ?",
      ar: "لماذا لا تفتح الصفحة؟",
    },
    answer: {
      de: "Prüfen Sie Ihre Internetverbindung, laden Sie die Seite neu und starten Sie notfalls den Browser neu. Bleibt es dabei, versuchen Sie es in einem anderen Browser.",
      en: "Check your internet connection, reload the page and, if needed, restart the browser. If it persists, try a different browser.",
      fr: "Vérifiez votre connexion, rechargez la page et, le cas échéant, redémarrez le navigateur. Si cela persiste, essayez un autre navigateur.",
      ar: "تحقق من اتصال الإنترنت وأعد تحميل الصفحة، وأعد تشغيل المتصفح عند الحاجة. إن استمرت المشكلة جرّب متصفحًا آخر.",
    },
    keywords: ["page", "open", "reload"],
  },
  {
    id: "tp-search",
    category: "technical",
    question: {
      de: "Warum funktioniert die Suche nicht?",
      en: "Why doesn't the search work?",
      fr: "Pourquoi la recherche ne fonctionne-t-elle pas ?",
      ar: "لماذا لا يعمل البحث؟",
    },
    answer: {
      de: "Prüfen Sie Ihre Eingaben und Filter. Wenn die Quelle gerade nicht erreichbar ist, klicken Sie auf erneuten Versuch – oft ist es ein vorübergehendes Problem.",
      en: "Check your input and filters. If the source is currently unreachable, click retry – it is often a transient issue.",
      fr: "Vérifiez votre saisie et vos filtres. Si la source est actuellement injoignable, cliquez sur réessayer – c'est souvent un problème transitoire.",
      ar: "تحقق من مدخلاتك وعوامل التصفية. وإذا كان المصدر غير متاح حاليًا، انقر إعادة المحاولة — غالبًا هو عارض.",
    },
    keywords: ["search", "work", "retry"],
  },
  {
    id: "tp-no-results",
    category: "technical",
    question: {
      de: "Warum werden keine Ergebnisse angezeigt?",
      en: "Why are no results shown?",
      fr: "Pourquoi aucun résultat n'est affiché ?",
      ar: "لماذا لا تظهر نتائج؟",
    },
    answer: {
      de: "Entfernen Sie zu enge Filter, erweitern Sie den Radius und verwenden Sie allgemeinere Suchbegriffe. Prüfen Sie zudem, ob das Ziel (Ausbildung oder Arbeit) korrekt gewählt ist.",
      en: "Remove filters that are too narrow, widen the radius and use more general terms. Also check that the goal (apprenticeship or job) is correctly chosen.",
      fr: "Retirez les filtres trop restrictifs, élargissez le rayon et utilisez des termes plus généraux. Vérifiez aussi que l'objectif (alternance ou emploi) est bien choisi.",
      ar: "أزل عوامل التصفية الضيقة، ووسّع النطاق، واستخدم كلمات أعم. وتأكّد أيضًا من اختيار الهدف (التدريب أو العمل) بشكل صحيح.",
    },
    keywords: ["no results", "filters", "empty"],
  },
  {
    id: "tp-ba-unavailable",
    category: "technical",
    question: {
      de: "Warum ist die Bundesagentur für Arbeit nicht verfügbar?",
      en: "Why is the Federal Employment Agency unavailable?",
      fr: "Pourquoi l'Agence fédérale pour l'emploi est-elle indisponible ?",
      ar: "لماذا وكالة العمل الاتحادية غير متاحة؟",
    },
    answer: {
      de: "Die Jobbörse kann vorübergehend überlastet oder nicht antwortend sein. Warten Sie kurz und versuchen Sie es erneut – in der KI-Suche liefern die anderen Quellen trotzdem Ergebnisse.",
      en: "The Jobbörse can be temporarily overloaded or not responding. Wait a moment and try again – in the AI Search, the other sources still deliver results.",
      fr: "La Jobbörse peut être temporairement surchargée ou ne pas répondre. Attendez un instant et réessayez – dans la Recherche IA, les autres sources livrent quand même des résultats.",
      ar: "قد تكون لوحة الوظائف مثقلة مؤقتًا أو لا تستجيب. انتظر قليلًا وأعد المحاولة — وفي البحث بالذكاء الاصطناعي تُقدّم المصادر الأخرى نتائج على أي حال.",
    },
    keywords: ["bundesagentur", "unavailable", "retry"],
  },
  {
    id: "tp-upload",
    category: "technical",
    question: {
      de: "Warum funktioniert der Upload nicht?",
      en: "Why doesn't the upload work?",
      fr: "Pourquoi le téléversement ne fonctionne-t-il pas ?",
      ar: "لماذا لا يعمل رفع الملفات؟",
    },
    answer: {
      de: "Prüfen Sie, ob der Dateityp erlaubt ist (z. B. PDF, DOC, DOCX, PNG, JPG) und ob die Datei die Größenbegrenzung einhält. Laden Sie eine gültige Datei erneut hoch.",
      en: "Check whether the file type is allowed (e.g. PDF, DOC, DOCX, PNG, JPG) and whether the file meets the size limit. Re-upload a valid file.",
      fr: "Vérifiez si le type de fichier est autorisé (p. ex. PDF, DOC, DOCX, PNG, JPG) et si le fichier respecte la limite de taille. Renvoyez un fichier valide.",
      ar: "تحقق من أن نوع الملف مسموح (مثل PDF وDOC وDOCX وPNG وJPG) وأن الملف يلتزم بالحد الأقصى. أعد رفع ملف صالح.",
    },
    keywords: ["upload", "file", "type"],
  },
  {
    id: "tp-pdf-analyze",
    category: "technical",
    question: {
      de: "Warum wird mein PDF nicht analysiert?",
      en: "Why isn't my PDF analyzed?",
      fr: "Pourquoi mon PDF n'est-il pas analysé ?",
      ar: "لماذا لا يُحلَّل ملف PDF الخاص بي؟",
    },
    answer: {
      de: "Prüfen Sie, ob das PDF gültig und lesbar ist und die Größenbegrenzung einhält. Manche gescannte oder sehr komplexe PDFs lassen sich schlechter lesen – versuchen Sie eine sauberere Version.",
      en: "Check that the PDF is valid, readable and meets the size limit. Some scanned or very complex PDFs are harder to read – try a cleaner version.",
      fr: "Vérifiez que le PDF est valide, lisible et respecte la limite de taille. Certains PDF scannés ou très complexes sont plus difficiles à lire – essayez une version plus propre.",
      ar: "تحقق من أن ملف PDF صالح وقابل للقراءة ويلتزم بالحد الأقصى. بعض الملفات الممسوحة أو المعقدة جدًا يصعب قراءتها — جرّب نسخة أنظف.",
    },
    keywords: ["pdf", "analyze", "scanner"],
  },
  {
    id: "tp-ai-no-answer",
    category: "technical",
    question: {
      de: "Warum antwortet die KI nicht?",
      en: "Why doesn't the AI answer?",
      fr: "Pourquoi l'IA ne répond-elle pas ?",
      ar: "لماذا لا يجيب الذكاء الاصطناعي؟",
    },
    answer: {
      de: "Prüfen Sie Ihre Verbindung und versuchen Sie es erneut. Falls Sie das tägliche Limit erreicht haben, können Sie am nächsten Tag weitermachen. Fragen außerhalb des Themas werden abgelehnt.",
      en: "Check your connection and try again. If you reached the daily limit, you can continue the next day. Out-of-topic questions are declined.",
      fr: "Vérifiez votre connexion et réessayez. Si vous avez atteint la limite quotidienne, vous pouvez reprendre le lendemain. Les questions hors sujet sont refusées.",
      ar: "تحقق من اتصالك وأعد المحاولة. وإذا كنت وصلت إلى الحد اليومي، يمكنك الاستمرار في اليوم التالي. والأسئلة خارج الموضوع تُرفض.",
    },
    keywords: ["ai", "no answer", "limit"],
  },
  {
    id: "tp-ai-slow",
    category: "technical",
    question: {
      de: "Warum ist die KI langsam?",
      en: "Why is the AI slow?",
      fr: "Pourquoi l'IA est-elle lente ?",
      ar: "لماذا يكون الذكاء الاصطناعي بطيئًا؟",
    },
    answer: {
      de: "Längere Antworten, mehrere Dateien oder eine hohe Auslastung können die Antwort verlangsamen. Die Antwort wird schrittweise angezeigt, sobald die KI arbeitet – geben Sie ihr etwas Zeit.",
      en: "Longer answers, several files or high load can slow the response. The answer is shown step by step as the AI works – give it a little time.",
      fr: "Des réponses plus longues, plusieurs fichiers ou une forte charge peuvent ralentir la réponse. La réponse s'affiche progressivement au travail de l'IA – laissez-lui un peu de temps.",
      ar: "الإجابات الطويلة أو عدة ملفات أو ضغط الاستخدام قد تُبطئ الرد. وتظهر الإجابة تدريجيًا بينما يعمل الذكاء الاصطناعي — امنحه بعض الوقت.",
    },
    keywords: ["ai", "slow", "load"],
  },
  {
    id: "tp-messages",
    category: "technical",
    question: {
      de: "Warum werden meine E-Mails nicht angezeigt?",
      en: "Why aren't my emails shown?",
      fr: "Pourquoi mes e-mails ne sont-ils pas affichés ?",
      ar: "لماذا لا تظهر رسائل بريدي؟",
    },
    answer: {
      de: "Prüfen Sie, ob Ihr E-Mail-Konto korrekt verknüpft ist, und öffnen Sie die Kampagne-Übersicht. Bei Problemen mit der Verknüpfung trennen und neu verbinden Sie das Konto.",
      en: "Check that your email account is correctly connected, and open the campaign overview. If the connection has issues, disconnect and reconnect the account.",
      fr: "Vérifiez que votre compte e-mail est correctement connecté, et ouvrez la vue de la campagne. En cas de problème de connexion, déconnectez puis reconnectez le compte.",
      ar: "تحقق من أن حساب البريد مربوط بشكل صحيح، وافتح صفحة الحملة. وفي حال وجود مشكلة في الربط، افصل الحساب ثم أعد ربطه.",
    },
    keywords: ["emails", "shown", "campaign"],
  },
  {
    id: "tp-save-job",
    category: "technical",
    question: {
      de: "Warum wird meine Stelle nicht gespeichert?",
      en: "Why isn't my job saved?",
      fr: "Pourquoi mon offre n'est-elle pas enregistrée ?",
      ar: "لماذا لا تُحفظ وظيفتي؟",
    },
    answer: {
      de: "Stellen Sie sicher, dass Sie angemeldet sind, und klicken Sie erneut auf das Lesezeichen. Prüfen Sie dann unter Gespeicherte Stellen, ob die Stelle dort auftaucht.",
      en: "Make sure you are signed in and click the bookmark again. Then check under Saved Opportunities whether the job appears there.",
      fr: "Assurez-vous d'être connecté et cliquez à nouveau sur le signet. Vérifiez ensuite sous Offres enregistrées si l'offre y apparaît.",
      ar: "تأكّد من تسجيل دخولك وانقر على أيقونة الإحفظ مجددًا. ثم تحقق من «الوظائف المحفوظة» إن ظهرت الوظيفة هناك.",
    },
    keywords: ["save", "job", "bookmark"],
  },
  {
    id: "tp-excel",
    category: "technical",
    question: {
      de: "Warum wird Excel nicht angezeigt?",
      en: "Why isn't Excel shown?",
      fr: "Pourquoi Excel n'est-il pas affiché ?",
      ar: "لماذا لا يظهر Excel؟",
    },
    answer: {
      de: "Der Export-Button ist nur aktiv, wenn es exportierbare Ergebnisse mit gültiger E-Mail gibt. Prüfen Sie, ob Ihre Ergebnisse eine E-Mail enthalten, und führen Sie die Suche ggf. erneut aus.",
      en: "The export button is only active when there are exportable results with a valid email. Check whether your results contain an email and, if needed, re-run the search.",
      fr: "Le bouton d'export n'est actif que s'il y a des résultats exportables avec un e-mail valide. Vérifiez si vos résultats contiennent un e-mail et, le cas échéant, relancez la recherche.",
      ar: "زر التصدير نشط فقط عندما تكون هناك نتائج قابلة للتصدير وتحمل بريدًا صحيحًا. تحقق من أن نتائجك تحتوي على بريد، وأعد تشغيل البحث عند الحاجة.",
    },
    keywords: ["excel", "export", "button"],
  },
  {
    id: "tp-download",
    category: "technical",
    question: {
      de: "Warum kann ich die Datei nicht herunterladen?",
      en: "Why can't I download the file?",
      fr: "Pourquoi ne puis-je pas télécharger le fichier ?",
      ar: "لماذا لا أستطيع تنزيل الملف؟",
    },
    answer: {
      de: "Prüfen Sie Ihre Internetverbindung und Ihre Browser-Einstellungen (Downloads erlauben). Schließen Sie offene Downloads nicht ab und versuchen Sie es erneut.",
      en: "Check your internet connection and your browser settings (allow downloads). Don't cancel open downloads and try again.",
      fr: "Vérifiez votre connexion et vos réglages du navigateur (autoriser les téléchargements). N'interrompez pas les téléchargements en cours et réessayez.",
      ar: "تحقق من اتصال الإنترنت وإعدادات متصفحك (السماح بالتنزيلات). لا تلغي التنزيلات الجارية وأعد المحاولة.",
    },
    keywords: ["download", "file", "browser"],
  },
  {
    id: "tp-error",
    category: "technical",
    question: {
      de: "Was tun, wenn ein Fehler erscheint?",
      en: "What to do when an error appears?",
      fr: "Que faire quand une erreur apparaît ?",
      ar: "ماذا أفعل عندما يظهر خطأ؟",
    },
    answer: {
      de: "Notieren Sie kurz, was Sie gemacht haben, laden Sie die Seite neu oder klicken Sie auf erneuten Versuch. Bleibt der Fehler, melden Sie ihn beim Plattform-Betreiber mit einer kurzen Beschreibung.",
      en: "Briefly note what you did, reload the page or click retry. If the error persists, report it to the platform owner with a short description.",
      fr: "Notez brièvement ce que vous avez fait, rechargez la page ou cliquez sur réessayer. Si l'erreur persiste, signalez-la au propriétaire de la plateforme avec une brève description.",
      ar: "دوّن باختصار ما فعلته، ثم أعد تحميل الصفحة أو انقر إعادة المحاولة. إن استمر الخطأ، أبلغ مالك المنصّة بوصف موجز.",
    },
    keywords: ["error", "report", "fix"],
  },
  {
    id: "tp-refresh",
    category: "technical",
    question: {
      de: "Hilft ein Refresh?",
      en: "Does a refresh help?",
      fr: "Un rechargement aide-t-il ?",
      ar: "هل تساعد إعادة التحميل؟",
    },
    answer: {
      de: "Oft ja – ein Neuladen stellt Verbindungen und Anzeige wieder her. Ihre gespeicherten Daten bleiben dabei erhalten.",
      en: "Often yes – a reload restores connections and display. Your saved data remains intact.",
      fr: "Souvent oui – un rechargement restaure les connexions et l'affichage. Vos données enregistrées restent intactes.",
      ar: "غالبًا نعم — إعادة التحميل تعيد الاتصال والعرض. وتبقى بياناتك المحفوظة سليمة.",
    },
    keywords: ["refresh", "reload", "help"],
  },
  {
    id: "tp-logout-login",
    category: "technical",
    question: {
      de: "Muss ich mich ab- und wieder anmelden?",
      en: "Do I have to log out and log back in?",
      fr: "Dois-je me déconnecter et me reconnecter ?",
      ar: "هل يجب عليّ تسجيل الخروج والدخول؟",
    },
    answer: {
      de: "Das kann helfen, wenn die Sitzung aus einem Grund ungültig ist. Ihre Daten bleiben dabei erhalten – es geht nichts verloren.",
      en: "That can help if the session is invalid for some reason. Your data remains intact – nothing is lost.",
      fr: "Cela peut aider si la session est invalide pour une raison. Vos données restent intactes – rien n'est perdu.",
      ar: "قد يساعد ذلك إذا كانت الجلسة غير صالحة لسبب ما. وتبقى بياناتك سليمة — لا يُفقد شيء.",
    },
    keywords: ["logout", "login", "session"],
  },
  {
    id: "tp-retry",
    category: "technical",
    question: {
      de: "Wann sollte ich 'erneut versuchen' verwenden?",
      en: "When should I use 'retry'?",
      fr: "Quand utiliser « réessayer » ?",
      ar: "متى يجب أن أستخدم «إعادة المحاولة»؟",
    },
    answer: {
      de: "Nutzen Sie erneuten Versuch, wenn eine Quelle vorübergehend nicht erreichbar war, eine Suche abgebrochen wurde oder ein Versand fehlschlug – etwa bei Netzwerk- oder Anbieterproblemen.",
      en: "Use retry when a source was temporarily unreachable, a search was interrupted or a send failed – e.g. on network or provider problems.",
      fr: "Utilisez réessayer quand une source était temporairement injoignable, une recherche a été interrompue ou un envoi a échoué – par exemple en cas de problème réseau ou fournisseur.",
      ar: "استخدم إعادة المحاولة عندما يكون المصدر غير متاح مؤقتًا، أو ينقطع البحث، أو يفشل الإرسال — مثل مشكلات الشبكة أو المزود.",
    },
    keywords: ["retry", "when", "transient"],
  },
];
