import type { DimensionId, DimensionStatus, MatchResult } from "./types";

/**
 * German UI vocabulary for the matching engine (professional, factual).
 * These are display labels only — all evidence sentences are generated by
 * the dimension evaluators from actual data.
 */

export const DIMENSION_LABELS: Record<DimensionId, string> = {
  goal: "Ziel",
  role: "Beruf / Tätigkeit",
  education: "Schulabschluss",
  skills: "Skills",
  experience: "Erfahrung",
  languages: "Sprachen",
  location: "Standort",
  relocation: "Umzugsbereitschaft",
  remote: "Home Office",
  employment: "Arbeitszeit",
  training_type: "Ausbildungsform",
  preferences: "Branchenpräferenz",
};

export const STATUS_LABELS: Record<DimensionStatus, string> = {
  match: "Erfüllt",
  partial: "Teilweise erfüllt",
  mismatch: "Nicht erfüllt",
  unknown: "Nicht bekannt",
  not_applicable: "Nicht anwendbar",
};

export const MATCH_STATUS_LABELS: Record<MatchResult["status"], string> = {
  complete: "Match",
  incomplete: "Match unvollständig",
  unavailable: "Match nicht verfügbar",
};

/** Human-readable score label, e.g. "85 %". */
export function formatMatchScore(score: number | null): string | null {
  return score === null ? null : `${score} %`;
}

/** The top missing-information lines for compact cards. */
export function topMissingInformation(
  result: MatchResult,
  limit = 2,
): string[] {
  return result.missing_information.slice(0, limit);
}
